// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tesisproject.backend.Data;

#nullable disable

namespace tesisproject.backend.Migrations.ProjectsDw
{
    [DbContext(typeof(ProjectsDwContext))]
    partial class ProjectsDwContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProjectsDW")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Bridges.BridgeProductAuthor", b =>
                {
                    b.Property<int>("BridgeProductAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BridgeProductAuthorId"));

                    b.Property<int>("AuthorKey")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<int>("FactProductId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryAuthor")
                        .HasColumnType("bit");

                    b.Property<string>("NameSnapshot")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Participation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductAuthorId")
                        .HasColumnType("int");

                    b.HasKey("BridgeProductAuthorId");

                    b.HasIndex("AuthorKey");

                    b.HasIndex("ProductAuthorId")
                        .IsUnique();

                    b.HasIndex("FactProductId", "AuthorKey")
                        .IsUnique();

                    b.ToTable("BridgeProductAuthors", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Bridges.BridgeProjectResearchCategory", b =>
                {
                    b.Property<int>("BridgeProjectResearchCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BridgeProjectResearchCategoryId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchCategoryKey")
                        .HasColumnType("int");

                    b.HasKey("BridgeProjectResearchCategoryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResearchCategoryKey");

                    b.HasIndex("ProjectId", "ResearchCategoryKey")
                        .IsUnique();

                    b.ToTable("BridgeProjectResearchCategories", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAuthor", b =>
                {
                    b.Property<int>("AuthorKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorKey"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalFullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ExternalResearcherId")
                        .HasColumnType("int");

                    b.Property<int?>("IdAsp")
                        .HasColumnType("int");

                    b.Property<bool>("IsInstitutional")
                        .HasColumnType("bit");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorKey");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.HasIndex("ExternalResearcherId");

                    b.HasIndex("IdAsp");

                    b.HasIndex("IsInstitutional");

                    b.ToTable("DimAuthors", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.HasIndex("Date");

                    b.HasIndex("Year", "Month");

                    b.ToTable("DimDates", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", b =>
                {
                    b.Property<int>("FacultyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyKey"));

                    b.Property<string>("FacultyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FacultyKey");

                    b.HasIndex("FacultyCode");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FacultyName");

                    b.ToTable("DimFaculties", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFundingType", b =>
                {
                    b.Property<int>("FundingTypeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FundingTypeKey"));

                    b.Property<int>("FundingTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FundingTypeKey");

                    b.HasIndex("FundingTypeId");

                    b.HasIndex("Name");

                    b.ToTable("DimFundingTypes", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingDatabase", b =>
                {
                    b.Property<int>("IndexingDatabaseKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexingDatabaseKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IndexingDatabaseKey");

                    b.HasIndex("Name");

                    b.ToTable("DimIndexingDatabases", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimJournal", b =>
                {
                    b.Property<int>("JournalKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JournalKey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DimJournals", "ProjectsDW", t =>
                        {
                            t.HasCheckConstraint("CK_DimJournals_Name_Trimmed", "[Name] <> N'' AND [Name] = LTRIM(RTRIM([Name]))");
                        });
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProductType", b =>
                {
                    b.Property<int>("ProductTypeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeKey"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductTypeKey");

                    b.HasIndex("Name");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("DimProductTypes", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProjectState", b =>
                {
                    b.Property<int>("ProjectStateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectStateKey"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProjectStateId")
                        .HasColumnType("int");

                    b.HasKey("ProjectStateKey");

                    b.HasIndex("Name");

                    b.HasIndex("ProjectStateId");

                    b.ToTable("DimProjectStates", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimQuartile", b =>
                {
                    b.Property<int>("QuartileKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuartileKey"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuartileKey");

                    b.HasIndex("Code");

                    b.ToTable("DimQuartiles", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimResearchCategory", b =>
                {
                    b.Property<int>("ResearchCategoryKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchCategoryKey"));

                    b.Property<string>("CategoryTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentCategoryKey")
                        .HasColumnType("int");

                    b.Property<int>("ResearchCategoryGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ResearchCategoryGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResearchCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchCategoryTypeId")
                        .HasColumnType("int");

                    b.HasKey("ResearchCategoryKey");

                    b.HasIndex("CategoryTypeName");

                    b.HasIndex("Name");

                    b.HasIndex("ParentCategoryKey");

                    b.HasIndex("ResearchCategoryGroupId");

                    b.HasIndex("ResearchCategoryGroupName");

                    b.HasIndex("ResearchCategoryId");

                    b.HasIndex("ResearchCategoryTypeId");

                    b.ToTable("DimResearchCategories", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactBudget", b =>
                {
                    b.Property<int>("FactBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactBudgetId"));

                    b.Property<int>("ApprovedDateKey")
                        .HasColumnType("int");

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<decimal>("CertifiedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExecutedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacultyKey")
                        .HasColumnType("int");

                    b.Property<int>("FundingTypeKey")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("FactBudgetId");

                    b.HasIndex("ApprovedDateKey");

                    b.HasIndex("BudgetId");

                    b.HasIndex("FacultyKey");

                    b.HasIndex("FundingTypeKey");

                    b.HasIndex("ProjectId");

                    b.ToTable("FactBudgets", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProduct", b =>
                {
                    b.Property<int>("FactProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactProductId"));

                    b.Property<int>("AuthorCount")
                        .HasColumnType("int");

                    b.Property<int>("CreatedDateKey")
                        .HasColumnType("int");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacultyKey")
                        .HasColumnType("int");

                    b.Property<int?>("IndexingDatabaseKey")
                        .HasColumnType("int");

                    b.Property<bool>("IsActiveFlag")
                        .HasColumnType("bit");

                    b.Property<string>("IssnIsbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JournalKey")
                        .HasColumnType("int");

                    b.Property<int>("ProductCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeKey")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int?>("QuartileKey")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("FactProductId");

                    b.HasIndex("CreatedDateKey");

                    b.HasIndex("FacultyKey");

                    b.HasIndex("IndexingDatabaseKey");

                    b.HasIndex("IsActiveFlag");

                    b.HasIndex("JournalKey");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeKey");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PublicationYear");

                    b.HasIndex("QuartileKey");

                    b.ToTable("FactProducts", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProject", b =>
                {
                    b.Property<int>("FactProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactProjectId"));

                    b.Property<int>("ApprovalDateKey")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<int?>("EndDateKey")
                        .HasColumnType("int");

                    b.Property<decimal>("ExecutionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacultyKey")
                        .HasColumnType("int");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectStateKey")
                        .HasColumnType("int");

                    b.Property<int>("StartDateKey")
                        .HasColumnType("int");

                    b.HasKey("FactProjectId");

                    b.HasIndex("ApprovalDateKey");

                    b.HasIndex("EndDateKey");

                    b.HasIndex("FacultyKey");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectStateKey");

                    b.HasIndex("StartDateKey");

                    b.ToTable("FactProjects", "ProjectsDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Bridges.BridgeProductAuthor", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAuthor", "Author")
                        .WithMany("ProductLinks")
                        .HasForeignKey("AuthorKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProduct", "Product")
                        .WithMany("Authors")
                        .HasForeignKey("FactProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Bridges.BridgeProjectResearchCategory", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasPrincipalKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimResearchCategory", "ResearchCategory")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("ResearchCategoryKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ResearchCategory");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactBudget", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "ApprovedDate")
                        .WithMany("ApprovedBudgets")
                        .HasForeignKey("ApprovedDateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", "Faculty")
                        .WithMany("Budgets")
                        .HasForeignKey("FacultyKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFundingType", "FundingType")
                        .WithMany("Budgets")
                        .HasForeignKey("FundingTypeKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovedDate");

                    b.Navigation("Faculty");

                    b.Navigation("FundingType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProduct", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "CreatedDate")
                        .WithMany("CreatedProducts")
                        .HasForeignKey("CreatedDateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", "Faculty")
                        .WithMany("Products")
                        .HasForeignKey("FacultyKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingDatabase", "IndexingDatabase")
                        .WithMany("Products")
                        .HasForeignKey("IndexingDatabaseKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimJournal", "Journal")
                        .WithMany("Products")
                        .HasForeignKey("JournalKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimQuartile", "Quartile")
                        .WithMany("Products")
                        .HasForeignKey("QuartileKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedDate");

                    b.Navigation("Faculty");

                    b.Navigation("IndexingDatabase");

                    b.Navigation("Journal");

                    b.Navigation("ProductType");

                    b.Navigation("Quartile");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProject", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "ApprovalDate")
                        .WithMany("ApprovalProjects")
                        .HasForeignKey("ApprovalDateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "EndDate")
                        .WithMany("EndProjects")
                        .HasForeignKey("EndDateKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", "Faculty")
                        .WithMany("Projects")
                        .HasForeignKey("FacultyKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProjectState", "ProjectState")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "StartDate")
                        .WithMany("StartProjects")
                        .HasForeignKey("StartDateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApprovalDate");

                    b.Navigation("EndDate");

                    b.Navigation("Faculty");

                    b.Navigation("ProjectState");

                    b.Navigation("StartDate");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAuthor", b =>
                {
                    b.Navigation("ProductLinks");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", b =>
                {
                    b.Navigation("ApprovalProjects");

                    b.Navigation("ApprovedBudgets");

                    b.Navigation("CreatedProducts");

                    b.Navigation("EndProjects");

                    b.Navigation("StartProjects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Products");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFundingType", b =>
                {
                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingDatabase", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimJournal", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProjectState", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimQuartile", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimResearchCategory", b =>
                {
                    b.Navigation("ProjectLinks");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactProduct", b =>
                {
                    b.Navigation("Authors");
                });
#pragma warning restore 612, 618
        }
    }
}
