services:
  api:
    build:
      context: .
      dockerfile: ./tesisproject.backend/Dockerfile
    container_name: tesisproject_api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080

      # Storage dentro del contenedor
      Storage__RootPath: /app/files

      # =========================
      # WINDOWS
      # Docker Desktop en Windows suele resolver host.docker.internal sin extra_hosts
      # =========================
      ConnectionStrings__DefaultConnection: >
        Server=${DB_HOST},${DB_PORT};
        Database=${DB_NAME};
        User Id=${DB_USER};
        Password=${DB_PASS};
        TrustServerCertificate=True;

      # =========================
      # LINUX
      # =========================
      # ConnectionStrings__DefaultConnection: >
      #   Server=${DB_HOST},${DB_PORT};
      #   Database=${DB_NAME};
      #   User Id=${DB_USER};
      #   Password=${DB_PASS};
      #   TrustServerCertificate=True;

    volumes:
      - type: bind
        source: ${STORAGE_HOST_PATH}
        target: /app/files

    # =========================
    # LINUX
    # =========================
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: ./tesisproject.frontend/Dockerfile
    container_name: tesisproject_web
    depends_on:
      - api
    ports:
      - "${WEB_HOST_PORT}:80"
    restart: unless-stopped