// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tesisproject.backend.DataWarehouse;

#nullable disable

namespace tesisproject.backend.Migrations.DwDb
{
    [DbContext(typeof(DwDbContext))]
    partial class DwDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimAcademicTerm", b =>
                {
                    b.Property<int>("AcademicTermKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicTermKey"));

                    b.Property<int>("AcademicTermId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcademicTermKey");

                    b.HasIndex("AcademicTermId");

                    b.ToTable("DimAcademicTerms");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimArticle", b =>
                {
                    b.Property<int>("ArticleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleKey"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Doi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filiacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasInterculturalComponent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProjectResult")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("ProceedingsName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicationUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleKey");

                    b.HasIndex("ArticleId");

                    b.ToTable("DimArticles");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimAuthor", b =>
                {
                    b.Property<int>("AuthorKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorKey"));

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Participacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("AuthorKey");

                    b.ToTable("DimAuthors");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quarter")
                        .HasColumnType("int");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.ToTable("DimDates");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimField", b =>
                {
                    b.Property<int>("FieldKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldKey"));

                    b.Property<int?>("BroadFieldId")
                        .HasColumnType("int");

                    b.Property<string>("BroadFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DetailedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("DetailedFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecificFieldId")
                        .HasColumnType("int");

                    b.Property<string>("SpecificFieldName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldKey");

                    b.HasIndex("DetailedFieldId");

                    b.ToTable("DimFields");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimIndexingSource", b =>
                {
                    b.Property<int>("IndexingSourceKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexingSourceKey"));

                    b.Property<int>("IndexingSourceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IndexingSourceKey");

                    b.HasIndex("IndexingSourceId");

                    b.ToTable("DimIndexingSources");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimProject", b =>
                {
                    b.Property<int>("ProjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectKey"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ProjectKey");

                    b.HasIndex("ProjectId");

                    b.ToTable("DimProjects");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimPublicationStatus", b =>
                {
                    b.Property<int>("PublicationStatusKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicationStatusKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("PublicationStatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("PublicationStatusKey");

                    b.HasIndex("PublicationStatusId");

                    b.ToTable("DimPublicationStatuses");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimResearchLine", b =>
                {
                    b.Property<int>("ResearchLineKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchLineKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResearchLineId")
                        .HasColumnType("int");

                    b.HasKey("ResearchLineKey");

                    b.HasIndex("ResearchLineId");

                    b.ToTable("DimResearchLines");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.DimVenue", b =>
                {
                    b.Property<int>("VenueKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueKey"));

                    b.Property<string>("IssnCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JournalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<string>("VolumeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VenueKey");

                    b.HasIndex("VenueId");

                    b.ToTable("DimVenues");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticleAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("AuthorIndex")
                        .HasColumnType("int");

                    b.Property<int>("AuthorKey")
                        .HasColumnType("int");

                    b.Property<int>("TotalAuthors")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorKey");

                    b.HasIndex("ArticleKey", "AuthorKey")
                        .IsUnique();

                    b.ToTable("FactArticleAuthors");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticleIndexing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("IndexedCount")
                        .HasColumnType("int");

                    b.Property<int>("IndexingSourceKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexingSourceKey");

                    b.HasIndex("ArticleKey", "IndexingSourceKey")
                        .IsUnique();

                    b.ToTable("FactArticleIndexings");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticlePublication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicTermKey")
                        .HasColumnType("int");

                    b.Property<int>("ArticleCount")
                        .HasColumnType("int");

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("AuthorCount")
                        .HasColumnType("int");

                    b.Property<int>("CreatedDateKey")
                        .HasColumnType("int");

                    b.Property<int?>("FieldKey")
                        .HasColumnType("int");

                    b.Property<bool>("HasInterculturalComponent")
                        .HasColumnType("bit");

                    b.Property<int>("IndexingCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpenAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProjectResult")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectKey")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationDateKey")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationStatusKey")
                        .HasColumnType("int");

                    b.Property<string>("Quartile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResearchLineKey")
                        .HasColumnType("int");

                    b.Property<decimal?>("SJR")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("VenueKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicTermKey");

                    b.HasIndex("ArticleKey");

                    b.HasIndex("CreatedDateKey");

                    b.HasIndex("FieldKey");

                    b.HasIndex("ProjectKey");

                    b.HasIndex("PublicationDateKey");

                    b.HasIndex("PublicationStatusKey");

                    b.HasIndex("ResearchLineKey");

                    b.HasIndex("VenueKey");

                    b.ToTable("FactArticlePublications");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactVenueMetricYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Quartile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SJR")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("VenueKey")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<int?>("YearDateKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("YearDateKey");

                    b.HasIndex("VenueKey", "Year")
                        .IsUnique();

                    b.ToTable("FactVenueMetricYears");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticleAuthor", b =>
                {
                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimAuthor", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticleIndexing", b =>
                {
                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimIndexingSource", "IndexingSource")
                        .WithMany()
                        .HasForeignKey("IndexingSourceKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("IndexingSource");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactArticlePublication", b =>
                {
                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimAcademicTerm", "AcademicTerm")
                        .WithMany()
                        .HasForeignKey("AcademicTermKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimDate", "CreatedDate")
                        .WithMany()
                        .HasForeignKey("CreatedDateKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimProject", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimDate", "PublicationDate")
                        .WithMany()
                        .HasForeignKey("PublicationDateKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimPublicationStatus", "PublicationStatus")
                        .WithMany()
                        .HasForeignKey("PublicationStatusKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimResearchLine", "ResearchLine")
                        .WithMany()
                        .HasForeignKey("ResearchLineKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimVenue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicTerm");

                    b.Navigation("Article");

                    b.Navigation("CreatedDate");

                    b.Navigation("Field");

                    b.Navigation("Project");

                    b.Navigation("PublicationDate");

                    b.Navigation("PublicationStatus");

                    b.Navigation("ResearchLine");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("tesisproject.backend.DataWarehouse.Entities.FactVenueMetricYear", b =>
                {
                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimVenue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.DataWarehouse.Entities.DimDate", "YearDate")
                        .WithMany()
                        .HasForeignKey("YearDateKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Venue");

                    b.Navigation("YearDate");
                });
#pragma warning restore 612, 618
        }
    }
}
