<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="QuestPDF">
      <HintPath>C:\Users\Personal\Source\Repos\TesisProject\tesisproject.backend\bin\Debug\net9.0\QuestPDF.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
