using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using tesisproject.backend.Controllers.Unified;
using tesisproject.backend.Data;
using tesisproject.backend.Data.UnifiedEntities.Catalogs;
using tesisproject.backend.Data.UnifiedEntities.Articles;
using tesisproject.backend.Repositories.Interfaces;
using tesisproject.backend.Options;
using tesisproject.backend.Repositories.Unified.Interfaces;
using tesisproject.backend.Repositories.Unified.Implementations;
using tesisproject.backend.Services.Interfaces;
using tesisproject.backend.Services.Implementations;
using tesisproject.backend.Services.Unified.Interfaces;
using tesisproject.backend.Services.Unified.Implementations;
using tesisproject.backend.UnitOfWork.Unified.Interfaces;
using tesisproject.backend.UnitOfWork.Unified.Implementations;

namespace tesisproject.backend.Services.Unified;

/// <summary>Isolated opt-in composition. Does not activate MVC routes, seed data or open a database.</summary>
public static class UnifiedApplicationRegistration
{
    public static IServiceCollection AddUnifiedDide(this IServiceCollection services,
        IConfiguration configuration, Action<DbContextOptionsBuilder> configureDatabase)
    {
        ArgumentNullException.ThrowIfNull(configuration);
        ArgumentNullException.ThrowIfNull(configureDatabase);
        // Mixing Identity stores or registering this composition twice is a configuration error.
        if (services.Any(d => d.ServiceType == typeof(IUnifiedUnitOfWork)
            || d.ServiceType == typeof(IUserStore<IdentityUser<int>>)
            || d.ServiceType == typeof(UnifiedDideDbContext)))
            throw new InvalidOperationException("Unified DIDE requires an isolated service collection without another Identity store or Unified composition.");
        services.AddSingleton(configuration);
        services.AddLogging();
        services.AddMemoryCache();
        services.AddHttpContextAccessor();
        services.AddAuthentication();
        services.AddRouting();
        services.AddAuthorization();
        services.AddDbContext<UnifiedDideDbContext>(configureDatabase);
        services.AddScoped<IUnifiedUnitOfWork, UnifiedUnitOfWork>();
        services.AddScoped<IUnifiedArticleRegistrationMatrixRepository, UnifiedArticleRegistrationMatrixRepository>();
        services.AddScoped<IGenericRepository<RegistrationMatrixColumn>, UnifiedGenericRepository<RegistrationMatrixColumn>>();
        services.AddScoped<IGenericRepository<RegistrationMatrixRow>, UnifiedGenericRepository<RegistrationMatrixRow>>();
        services.AddScoped<IGenericRepository<RegistrationMatrixCell>, UnifiedGenericRepository<RegistrationMatrixCell>>();
        services.AddScoped<IGenericRepository<FieldCatalogEntry>, UnifiedGenericRepository<FieldCatalogEntry>>();
        services.AddScoped<IUnifiedArticleReadRepository, UnifiedArticleReadRepository>();
        services.AddScoped<IUnifiedArticleQueryService, UnifiedArticleQueryService>();
        services.AddScoped<UnifiedArticlesController>();
        services.AddScoped<UnifiedArticlesConfigurationController>();
        services.AddScoped<UnifiedArticlesCatalogsController>();
        services.AddScoped<UnifiedArticlesRegistrationMatricesController>();
        services.AddScoped<IUnifiedArticleUserContext, UnifiedArticleUserContext>();
        services.AddScoped<IUnifiedCurrentSessionService, UnifiedCurrentSessionService>();
        services.AddScoped<IUnifiedRegistrationMatrixService, UnifiedRegistrationMatrixService>();
        services.AddScoped<IUnifiedArticleConfigurationRepository, UnifiedArticleConfigurationRepository>();
        services.AddScoped<IUnifiedArticleConfigurationService, UnifiedArticleConfigurationService>();
        services.AddScoped<IUnifiedArticleRegistrationRepository, UnifiedArticleRegistrationRepository>();
        services.AddScoped<IUnifiedArticleFormSelector, UnifiedArticleFormSelector>();
        services.AddScoped<IUnifiedArticleRegistrationCommandService, UnifiedArticleRegistrationCommandService>();
        services.AddScoped<ICurrentUserService, CurrentUserService>();
        services.AddScoped<ITokenService, JwtTokenService>();
        services.AddOptions<ExternalApiOptions>().Bind(configuration.GetSection(ExternalApiOptions.SectionName))
            .ValidateDataAnnotations().ValidateOnStart();
        services.AddOptions<StorageOptions>().Bind(configuration.GetSection(StorageOptions.SectionName))
            .Validate(o => !string.IsNullOrWhiteSpace(o.RootPath), "Storage:RootPath is required").ValidateOnStart();
        services.AddOptions<DocumentRecognitionOptions>().Bind(configuration.GetSection(DocumentRecognitionOptions.SectionName))
            .ValidateDataAnnotations().ValidateOnStart();
        services.AddHttpClient("ExternalApi").ConfigureHttpClient((sp, client) =>
        {
            var options = sp.GetRequiredService<IOptions<ExternalApiOptions>>().Value;
            client.BaseAddress = new Uri(options.BaseUrl);
            client.Timeout = TimeSpan.FromSeconds(options.TimeoutSeconds);
            if (!string.IsNullOrWhiteSpace(options.UserAgent))
                client.DefaultRequestHeaders.Add("User-Agent", options.UserAgent);
        });
        services.AddHttpClient<IExternalDirectoryClient, ExternalDirectoryClient>("ExternalApi");
        services.AddHttpClient<IExternalPeriodsClient, ExternalPeriodsClient>("ExternalApi");
        services.AddHttpClient<IExternalAcademicsService, ExternalAcademicsService>("ExternalApi");
        services.AddHttpClient<IExternalDistributivosService, ExternalDistributivosService>("ExternalApi");
        services.AddHttpClient<IUnifiedAcademicCatalogSnapshotClient, UnifiedAcademicCatalogSnapshotClient>("ExternalApi");
        services.AddScoped<IUnifiedFacultySynchronizationService, UnifiedFacultySynchronizationService>();
        services.AddScoped<IUnifiedAcademicTermSynchronizationService, UnifiedAcademicTermSynchronizationService>();
        services.AddScoped<UnifiedCatalogSynchronizationController>();
        services.AddScoped<IUnifiedFacultyQueryService, UnifiedFacultyQueryService>();
        services.AddScoped<UnifiedFacultiesController>();
        services.AddUnifiedIdentityBoundary();
        services.AddScoped<IUnifiedFacultyRepository, UnifiedFacultyRepository>();
        services.AddScoped<IUnifiedAcademicTermRepository, UnifiedAcademicTermRepository>();
        services.AddScoped<IUnifiedAppConfigurationRepository, UnifiedAppConfigurationRepository>();
        services.AddScoped<IUnifiedAppUserRepository, UnifiedAppUserRepository>();
        services.AddScoped<IUnifiedAuthorRepository, UnifiedAuthorRepository>();
        services.AddScoped<IUnifiedBudgetRepository, UnifiedBudgetRepository>();
        services.AddScoped<IUnifiedConvocationRepository, UnifiedConvocationRepository>();
        services.AddScoped<IUnifiedDocumentRepository, UnifiedDocumentRepository>();
        services.AddScoped<IUnifiedExportFieldRepository, UnifiedExportFieldRepository>();
        services.AddScoped<IUnifiedExportTemplateColumnRepository, UnifiedExportTemplateColumnRepository>();
        services.AddScoped<IUnifiedExportTemplateRepository, UnifiedExportTemplateRepository>();
        services.AddScoped<IUnifiedExternalResearcherProjectRepository, UnifiedExternalResearcherProjectRepository>();
        services.AddScoped<IUnifiedExternalResearcherRepository, UnifiedExternalResearcherRepository>();
        services.AddScoped<IUnifiedFacultyScopeFacultyRepository, UnifiedFacultyScopeFacultyRepository>();
        services.AddScoped<IUnifiedFacultyScopeRepository, UnifiedFacultyScopeRepository>();
        services.AddScoped<IUnifiedGroupMemberRepository, UnifiedGroupMemberRepository>();
        services.AddScoped<IUnifiedGroupRepository, UnifiedGroupRepository>();
        services.AddScoped<IUnifiedObjectiveActivityRepository, UnifiedObjectiveActivityRepository>();
        services.AddScoped<IUnifiedObjectiveActivityUserRepository, UnifiedObjectiveActivityUserRepository>();
        services.AddScoped<IUnifiedProductAuthorRepository, UnifiedProductAuthorRepository>();
        services.AddScoped<IUnifiedProductAttributeDefinitionRepository, UnifiedProductAttributeDefinitionRepository>();
        services.AddScoped<IUnifiedProductRepository, UnifiedProductRepository>();
        services.AddScoped<IUnifiedProductValueRepository, UnifiedProductValueRepository>();
        services.AddScoped<IUnifiedProjectDocumentRepository, UnifiedProjectDocumentRepository>();
        services.AddScoped<IUnifiedProjectExtensionRepository, UnifiedProjectExtensionRepository>();
        services.AddScoped<IUnifiedProjectObjectiveRepository, UnifiedProjectObjectiveRepository>();
        services.AddScoped<IUnifiedProjectRepository, UnifiedProjectRepository>();
        services.AddScoped<IUnifiedProjectResearchCategoryRepository, UnifiedProjectResearchCategoryRepository>();
        services.AddScoped<IUnifiedResearchCategoryRepository, UnifiedResearchCategoryRepository>();
        services.AddScoped<IUnifiedUserFacultyScopeAssignmentRepository, UnifiedUserFacultyScopeAssignmentRepository>();
        services.AddScoped<IUnifiedVisitIssueRepository, UnifiedVisitIssueRepository>();
        services.AddScoped<IUnifiedVisitObjectiveActivityProgressRepository, UnifiedVisitObjectiveActivityProgressRepository>();
        services.AddScoped<IUnifiedVisitRepository, UnifiedVisitRepository>();
        services.AddScoped<IUnifiedCatalogRepository<Country>, UnifiedCatalogRepository<Country>>();
        services.AddScoped<IUnifiedCatalogRepository<DocumentType>, UnifiedCatalogRepository<DocumentType>>();
        services.AddScoped<IUnifiedCatalogRepository<FundingType>, UnifiedCatalogRepository<FundingType>>();
        services.AddScoped<IUnifiedCatalogRepository<IndexingSource>, UnifiedCatalogRepository<IndexingSource>>();
        services.AddScoped<IUnifiedCatalogRepository<Institution>, UnifiedCatalogRepository<Institution>>();
        services.AddScoped<IUnifiedCatalogRepository<MemberRoleType>, UnifiedCatalogRepository<MemberRoleType>>();
        services.AddScoped<IUnifiedCatalogRepository<ObjectiveType>, UnifiedCatalogRepository<ObjectiveType>>();
        services.AddScoped<IUnifiedCatalogRepository<ProductAttribute>, UnifiedCatalogRepository<ProductAttribute>>();
        services.AddScoped<IUnifiedCatalogRepository<ProductType>, UnifiedCatalogRepository<ProductType>>();
        services.AddScoped<IUnifiedCatalogRepository<ProjectExtensionType>, UnifiedCatalogRepository<ProjectExtensionType>>();
        services.AddScoped<IUnifiedCatalogRepository<ProjectOriginType>, UnifiedCatalogRepository<ProjectOriginType>>();
        services.AddScoped<IUnifiedCatalogRepository<ProjectState>, UnifiedCatalogRepository<ProjectState>>();
        services.AddScoped<IUnifiedCatalogRepository<ProjectType>, UnifiedCatalogRepository<ProjectType>>();
        services.AddScoped<IUnifiedCatalogRepository<ResearchCategoryGroup>, UnifiedCatalogRepository<ResearchCategoryGroup>>();
        services.AddScoped<IUnifiedCatalogRepository<ResearchCategoryType>, UnifiedCatalogRepository<ResearchCategoryType>>();
        services.AddScoped<IUnifiedCatalogRepository<TransactionType>, UnifiedCatalogRepository<TransactionType>>();
        services.AddScoped<IUnifiedCatalogRepository<VisitState>, UnifiedCatalogRepository<VisitState>>();
        services.AddScoped<IUnifiedAuthorService, UnifiedAuthorService>();
        services.AddScoped<IUnifiedAuthService, UnifiedAuthService>();
        services.AddScoped<IUnifiedBudgetService, UnifiedBudgetService>();
        services.AddScoped(typeof(IUnifiedCatalogCrudService<>), typeof(UnifiedCatalogCrudService<>));
        services.AddScoped<IUnifiedCatalogQueryService, UnifiedCatalogQueryService>();
        services.AddScoped<IUnifiedConvocationService, UnifiedConvocationService>();
        services.AddScoped<IUnifiedCountryService, UnifiedCountryService>();
        services.AddScoped<IUnifiedDocumentRecognitionService, UnifiedDocumentRecognitionService>();
        services.AddScoped<IUnifiedDocumentService, UnifiedDocumentService>();
        services.AddScoped<IUnifiedExportTemplateExcelService, UnifiedExportTemplateExcelService>();
        services.AddScoped<IUnifiedExportTemplateService, UnifiedExportTemplateService>();
        services.AddScoped<IUnifiedExternalResearcherProjectService, UnifiedExternalResearcherProjectService>();
        services.AddScoped<IUnifiedExternalResearcherService, UnifiedExternalResearcherService>();
        services.AddScoped<IUnifiedFacultyScopeService, UnifiedFacultyScopeService>();
        services.AddScoped<IUnifiedGroupService, UnifiedGroupService>();
        services.AddScoped<IUnifiedIndexingSourceService, UnifiedIndexingSourceService>();
        services.AddScoped<IUnifiedInstitutionService, UnifiedInstitutionService>();
        services.AddScoped<IUnifiedMatrixExcelExportService, UnifiedMatrixExcelExportService>();
        services.AddScoped<IUnifiedMatrixTemplateExcelExportService, UnifiedMatrixTemplateExcelExportService>();
        services.AddScoped<IUnifiedMemberRoleTypeService, UnifiedMemberRoleTypeService>();
        services.AddScoped<IUnifiedObjectiveActivityService, UnifiedObjectiveActivityService>();
        services.AddScoped<IUnifiedObjectiveActivityUserService, UnifiedObjectiveActivityUserService>();
        services.AddScoped<IUnifiedProductAttributeDefinitionService, UnifiedProductAttributeDefinitionService>();
        services.AddScoped<IUnifiedProductAttributeService, UnifiedProductAttributeService>();
        services.AddScoped<IUnifiedProductService, UnifiedProductService>();
        services.AddScoped<IUnifiedProductTypeDesignService, UnifiedProductTypeDesignService>();
        services.AddScoped<IUnifiedProjectExtensionService, UnifiedProjectExtensionService>();
        services.AddScoped<IUnifiedProjectFlatReportService, UnifiedProjectFlatReportService>();
        services.AddScoped<IUnifiedProjectMatrixService, UnifiedProjectMatrixService>();
        services.AddScoped<IUnifiedProjectObjectiveService, UnifiedProjectObjectiveService>();
        services.AddScoped<IUnifiedProjectResearchCategoryService, UnifiedProjectResearchCategoryService>();
        services.AddScoped<IUnifiedProjectService, UnifiedProjectService>();
        services.AddScoped<IUnifiedProjectsFiltersService, UnifiedProjectsFiltersService>();
        services.AddScoped<IUnifiedRefreshTokenService, UnifiedRefreshTokenService>();
        services.AddScoped<IUnifiedResearchCategoryService, UnifiedResearchCategoryService>();
        services.AddScoped<IUnifiedResearchCategoryTypeService, UnifiedResearchCategoryTypeService>();
        services.AddScoped<IUnifiedVisitIssueService, UnifiedVisitIssueService>();
        services.AddScoped<IUnifiedVisitObjectiveActivityProgressService, UnifiedVisitObjectiveActivityProgressService>();
        services.AddScoped<IUnifiedVisitService, UnifiedVisitService>();
        services.AddScoped<UnifiedAcademicPeriodsController>();
        services.AddScoped<UnifiedAuthController>();
        services.AddScoped<UnifiedBudgetsController>();
        services.AddScoped<UnifiedConvocationsController>();
        services.AddScoped<UnifiedCountriesController>();
        services.AddScoped<UnifiedDocumentRecognitionController>();
        services.AddScoped<UnifiedDocumentsController>();
        services.AddScoped<UnifiedDocumentTypesController>();
        services.AddScoped<UnifiedExportTemplatesController>();
        services.AddScoped<UnifiedExternalAcademicsController>();
        services.AddScoped<UnifiedExternalPeriodsController>();
        services.AddScoped<UnifiedExternalResearcherProjectsController>();
        services.AddScoped<UnifiedExternalResearchersController>();
        services.AddScoped<UnifiedFacultyScopesController>();
        services.AddScoped<UnifiedFundingTypesController>();
        services.AddScoped<UnifiedGroupsController>();
        services.AddScoped<UnifiedIndexingSourcesController>();
        services.AddScoped<UnifiedInstitutionsController>();
        services.AddScoped<UnifiedMemberRoleTypesController>();
        services.AddScoped<UnifiedObjectiveActivitiesController>();
        services.AddScoped<UnifiedObjectiveActivityUsersController>();
        services.AddScoped<UnifiedObjectiveTypesController>();
        services.AddScoped<UnifiedProductAttributeDefinitionsController>();
        services.AddScoped<UnifiedProductAttributesController>();
        services.AddScoped<UnifiedProductsController>();
        services.AddScoped<UnifiedProductTypeDesignController>();
        services.AddScoped<UnifiedProductTypesController>();
        services.AddScoped<UnifiedProjectExtensionsController>();
        services.AddScoped<UnifiedProjectExtensionTypesController>();
        services.AddScoped<UnifiedProjectMatrixController>();
        services.AddScoped<UnifiedProjectObjectivesController>();
        services.AddScoped<UnifiedProjectOriginTypesController>();
        services.AddScoped<UnifiedProjectResearchCategoryController>();
        services.AddScoped<UnifiedProjectsController>();
        services.AddScoped<UnifiedProjectsFiltersController>();
        services.AddScoped<UnifiedProjectStatesController>();
        services.AddScoped<UnifiedProjectTypesController>();
        services.AddScoped<UnifiedResearchCategoriesController>();
        services.AddScoped<UnifiedResearchCategoryGroupsController>();
        services.AddScoped<UnifiedResearchCategoryTypeController>();
        services.AddScoped<UnifiedTransactionTypesController>();
        services.AddScoped<UnifiedVisitIssuesController>();
        services.AddScoped<UnifiedVisitObjectiveActivityProgressesController>();
        services.AddScoped<UnifiedVisitsController>();
        services.AddScoped<UnifiedVisitStatesController>();
        return services;
    }
}
