// Generated once from the approved Projects catalog seed. This C# file is the canonical runtime source.
using tesisproject.backend.Data.UnifiedEntities.Catalogs;
using tesisproject.backend.Data.UnifiedEntities.Core;
using tesisproject.backend.Data.UnifiedEntities.Core.Products;
using tesisproject.backend.Data.UnifiedEntities.Export;
using tesisproject.backend.Services.Unified.Implementations.DataMigrations;

namespace tesisproject.backend.Services.Unified.DataMigrations.ProjectsInitialCatalog;

internal static class ProjectsSeedData
{
    public static IReadOnlyList<IProjectsSeedTable> Tables { get; } =
    [

        new ProjectsSeedTable<DocumentType, DocumentTypesRow>("DocumentTypes", [
            new(1, "Memorando inicial", true, false),
            new(2, "Memorando Informe Final", true, false),
            new(3, "Resolucion Prorroga", true, false),
            new(4, "Resolucion Informe Final", true, false),
            new(5, "Contrato Auspicio", true, false),
            new(6, "Resolucion de visita", true, false),
        ]),
        new ProjectsSeedTable<GroupType, GroupTypesRow>("GroupTypes", [
            new(1, "Integrantes", true, false),
            new(2, "Investigadores", true, false),
        ]),
        new ProjectsSeedTable<Convocation, ConvocationsRow>("Convocations", [
            new(1, "SIN CONVOCATORIA", null, true, false),
            new(2, "CEDIA I+D+i 2022", null, true, false),
            new(3, "CEDIA I+D+i 2023", null, true, false),
            new(4, "CEDIA I+D+i-2023", null, true, false),
            new(5, "CEDIA I+D+i-2024", null, true, false),
            new(6, "CEPRA 2022", null, true, false),
            new(7, "CONVENIO CON UNIVERSIDAD DE COMPOSTELA", null, true, false),
            new(8, "CONVENIO INTERINSTITUCIONAL POLITECNICA DE CHIMBORAZA Y LA UTA", null, true, false),
            new(9, "CONVOCATORI PRESELECCIÓN PERSONAL ACADÉMICO", null, true, false),
            new(10, "CONVOCATORIA", null, true, false),
            new(11, "CONVOCATORIA ABIERTA", null, true, false),
            new(12, "CONVOCATORIA ADSIDEO COOPERACION 2021", null, true, false),
            new(13, "CONVOCATORIA DOCENTES DIDE", null, true, false),
            new(14, "CONVOCATORIA I + D + I 2024 DOCENTES DIDE", null, true, false),
            new(15, "CONVOCATORIA I + D + i 2024 DOCENTES CINTRATADOS POR DIDE", null, true, false),
            new(16, "CONVOCATORIA I+D 2022", null, true, false),
            new(17, "CONVOCATORIA I+D 2022 DOCENTE DIDE", null, true, false),
            new(18, "CONVOCATORIA I+D 2023", null, true, false),
            new(19, "CONVOCATORIA I+D 2024 DOCENTE DIDE", null, true, false),
            new(20, "CONVOCATORIA I+D+I 2023", null, true, false),
            new(21, "CONVOCATORIA I+D+I 2024", null, true, false),
            new(22, "CONVOCATORIA I+D+i 2020", null, true, false),
            new(23, "CONVOCATORIA I+D+i 2021", null, true, false),
            new(24, "CONVOCATORIA I+D+i 2023", null, true, false),
            new(25, "CONVOCATORIA I+D+i 2024", null, true, false),
            new(26, "CONVOCATORIA I+D+i 2025", null, true, false),
            new(27, "CONVOCATORIA I+D+i 2025 - 2026", null, true, false),
            new(28, "CONVOCATORIA I+D+i 2025-2026", null, true, false),
            new(29, "CONVOCATORIA I+D+i2025-2026", null, true, false),
            new(30, "CONVOCATORIA IMPLEMENTACIÓN DE LABORATORIOS", null, true, false),
            new(31, "CONVOCATORIA PARA LA APROBACIÓN DE PROYECTOS DODENTES DIDE", null, true, false),
            new(32, "CONVOCATORIA PARA LA APROBACIÓN Y FINANCIAMIENTO DE PROYECTOS DE INVESTIGACIÓN I+D+i 2025 - 2026", null, true, false),
            new(33, "CONVOCATORIA PARA LA APROBACIÓN Y FINANCIAMIENTO I + D + i 2024 DOCENTES DIDE", null, true, false),
            new(34, "CONVOCATORIA PRESELECCIÓN PERSONAL ACADÉMICO", null, true, false),
            new(35, "CONVOCATORIA SEPTIEMBRE 2018 - FEBRERO 2019", null, true, false),
            new(36, "Convocatoria Abierta para el Financiamiento de Proyectos de Investigación e Innovación I+D+i", null, true, false),
            new(37, "Convocatoria KUKA", null, true, false),
            new(38, "DOCENTE DIDE", null, true, false),
            new(39, "EXTERNO", null, true, false),
            new(40, "FIASA", null, true, false),
            new(41, "Financiamiento de Proyectos de Investigación e Innovación I+D+i\"", null, true, false),
            new(42, "IX CEDIA-CEPRA-2015", null, true, false),
            new(43, "Mar-Ago 2018", null, true, false),
            new(44, "PRESENTA INFORME FINAL CON OFICIO UTA-FISEI-202-0517-M DEL 07-03-2022", null, true, false),
            new(45, "PROYECTO VLIR CONVOCATORIA TEAM PROJECT 2022", null, true, false),
            new(46, "SENESCYT", null, true, false),
            new(47, "UTA-FCIAB-2021-1267-M", null, true, false),
        ]),
        new ProjectsSeedTable<ProjectState, ProjectStatesRow>("ProjectStates", [
            new(1, "FINALIZADO", true, true),
            new(2, "EN CIERRE", true, true),
            new(3, "EN EJECUCION", true, true),
            new(4, "DETENIDO", true, true),
            new(5, "CANCELADO", true, true),
            new(6, "PLANIFICADO", true, true),
        ]),
        new ProjectsSeedTable<ProjectType, ProjectTypesRow>("ProjectTypes", [
            new(1, "Aplicada", true, true),
            new(2, "Experimental", true, true),
        ]),
        new ProjectsSeedTable<TransactionType, TransactionTypesRow>("TransactionTypes", [
            new(1, "Certificacion", true, true),
            new(2, "Devengado", true, true),
            new(3, "Anulacion", true, false),
        ]),
        new ProjectsSeedTable<VisitState, VisitStatesRow>("VisitStates", [
            new(1, "Creada", true, true),
            new(2, "Planificada", true, true),
            new(3, "Realizada", true, true),
            new(4, "Pendiente", true, true),
        ]),
        new ProjectsSeedTable<ObjectiveType, ObjectiveTypesRow>("ObjectiveTypes", [
            new(1, "General", true, true),
            new(2, "Especifico", true, true),
        ]),
        new ProjectsSeedTable<ResearchCategoryGroup, ResearchCategoryGroupsRow>("ResearchCategoryGroups", [
            new(1, "Áreas de Investigación", true, false),
            new(2, "Campos de Conocimiento", true, false),
            new(3, "Alcances", true, false),
            new(4, "Impactos", true, false),
        ]),
        new ProjectsSeedTable<ResearchCategoryType, ResearchCategoryTypesRow>("ResearchCategoryTypes", [
            new(1, "Dominio", 1, true, true, false),
            new(2, "Línea de investigación", 1, true, true, false),
            new(3, "Sub-línea de investigación", 1, true, true, false),
            new(4, "Campo amplio", 2, true, true, false),
            new(5, "Campo específico", 2, true, true, false),
            new(6, "Campo detallado", 2, true, true, false),
            new(7, "Alcance Territorial", 3, true, true, false),
            new(8, "Impacto Esperado", 4, true, true, false),
        ]),
        new ProjectsSeedTable<ResearchCategory, ResearchCategoriesRow>("ResearchCategories", [
            new(1, 1, null, "Fortalecimiento social, democrático y educativo", true, false),
            new(2, 1, null, "Optimización de los sistemas productivos, técnicos-tecnológicos y desarrollo urbanístico", true, false),
            new(3, 1, null, "Desarrollo económico, productivo empresarial", true, false),
            new(4, 1, null, "Sistemas alimentarios, nutrición y salud pública", true, false),
            new(101, 2, 1, "Exclusión e Integración Social", true, false),
            new(102, 2, 1, "Políticas Públicas, Derecho y Sociedad", true, false),
            new(103, 2, 1, "Comunicación, Sociedad, Cultura y Tecnología", true, false),
            new(104, 2, 1, "Comportamiento Social y Educativo", true, false),
            new(105, 2, 1, "Inclusión, Igualdad de oportunidades e Interculturalidad", true, false),
            new(106, 2, 2, "Construcción, Estructuras, Vías, Tránsito y Transporte", true, false),
            new(107, 2, 2, "Desarrollo y Ordenamiento Territorial", true, false),
            new(108, 2, 2, "Energía, Desarrollo Sostenible y Gestión de Recursos Naturales", true, false),
            new(109, 2, 2, "Salud y Bienestar", true, false),
            new(110, 2, 2, "Diseño, Materiales, Producción, Identidad, Sostenibilidad y Tecnologías aplicadas", true, false),
            new(111, 2, 2, "Software, Tecnologías de la Información y Ciencia de Datos", true, false),
            new(112, 2, 2, "Electrónica, Telecomunicaciones y Sistemas de Control", true, false),
            new(113, 2, 2, "Arquitectura, Construcción, Territorio y Paisaje", true, false),
            new(114, 2, 3, "Desarrollo Sostenible e Innovación Empresarial", true, false),
            new(115, 2, 3, "Economía del Desarrollo", true, false),
            new(116, 2, 4, "Salud Humana", true, false),
            new(117, 2, 4, "Salud Animal", true, false),
            new(118, 2, 4, "Seguridad y Soberanía Alimentaria", true, false),
            new(119, 2, 4, "Producción Agroalimentaria y Medio Ambiente", true, false),
            new(120, 2, 4, "Microbiología y Biotecnología", true, false),
            new(2001, 4, null, "Educación", true, false),
            new(2002, 4, null, "Artes y humanidades", true, false),
            new(2003, 4, null, "Ciencias sociales, periodismo, información y derecho", true, false),
            new(2004, 4, null, "Administración", true, false),
            new(2005, 4, null, "Ciencias naturales, matemáticas y estadísticas", true, false),
            new(2006, 4, null, "Tecnologías de la información y la comunicación (TIC)", true, false),
            new(2007, 4, null, "Ingeniería, industría y construcción", true, false),
            new(2008, 4, null, "Agricultura, silvicultura, pesca y veterinaria", true, false),
            new(2009, 4, null, "Salud y Bienestar", true, false),
            new(2010, 4, null, "Servicios", true, false),
            new(2101, 5, 2001, "Educación", true, false),
            new(2102, 5, 2002, "Artes", true, false),
            new(2103, 5, 2002, "Humanidades", true, false),
            new(2104, 5, 2002, "Idiomas", true, false),
            new(2105, 5, 2003, "Ciencias sociales y del comportamiento", true, false),
            new(2106, 5, 2003, "Periodismo e información", true, false),
            new(2107, 5, 2003, "Derecho", true, false),
            new(2108, 5, 2004, "Educación comercial y administración", true, false),
            new(2109, 5, 2005, "Ciencias biológicas y afines", true, false),
            new(2110, 5, 2005, "Medio ambiente", true, false),
            new(2111, 5, 2005, "Ciencias físicas", true, false),
            new(2112, 5, 2005, "Matemáticas y estadística", true, false),
            new(2113, 5, 2006, "Tecnologías de la información y la comunicación (TIC)", true, false),
            new(2114, 5, 2007, "Ingeniaría y profesiones afines", true, false),
            new(2115, 5, 2007, "Industría y producción", true, false),
            new(2116, 5, 2007, "Arquitectura y construcción", true, false),
            new(2117, 5, 2008, "Agricultura", true, false),
            new(2118, 5, 2008, "Silvicultura", true, false),
            new(2119, 5, 2008, "Pesca", true, false),
            new(2120, 5, 2008, "Veterinaria", true, false),
            new(2121, 5, 2009, "Salud", true, false),
            new(2122, 5, 2009, "Bienestar", true, false),
            new(2123, 5, 2010, "Servicios personales", true, false),
            new(2124, 5, 2010, "Servicios de protección", true, false),
            new(2125, 5, 2010, "Servicios de seguridad", true, false),
            new(2126, 5, 2010, "Servicio de transporte", true, false),
            new(2201, 6, 2101, "Educación", true, false),
            new(2202, 6, 2101, "Psicopedagogía", true, false),
            new(2203, 6, 2101, "Formación para docentes de educación preprimaria", true, false),
            new(2204, 6, 2101, "Formación para docentes sin asignaturas de especialización", true, false),
            new(2205, 6, 2101, "Formación para docentes con asignaturas de especialización", true, false),
            new(2210, 6, 2102, "Técnicas audiovisuales y producción para medios de comunicación", true, false),
            new(2211, 6, 2102, "Diseño", true, false),
            new(2212, 6, 2102, "Artes", true, false),
            new(2213, 6, 2102, "Música y artes escénicas", true, false),
            new(2220, 6, 2103, "Religión y Teología", true, false),
            new(2221, 6, 2103, "Historia y Arqueología", true, false),
            new(2222, 6, 2103, "Filosofía", true, false),
            new(2230, 6, 2104, "Idiomas", true, false),
            new(2231, 6, 2104, "Literatura y lingüística", true, false),
            new(2240, 6, 2105, "Economía", true, false),
            new(2241, 6, 2105, "Economía Matemática", true, false),
            new(2242, 6, 2105, "Ciencias políticas", true, false),
            new(2243, 6, 2105, "Psicología", true, false),
            new(2244, 6, 2105, "Estudios Sociales y Culturales", true, false),
            new(2245, 6, 2105, "Estudios de Género", true, false),
            new(2246, 6, 2105, "Geografía y territorio", true, false),
            new(2250, 6, 2106, "Periodismo y comunicación", true, false),
            new(2251, 6, 2106, "Bibliotecología, documentación y archivología", true, false),
            new(2260, 6, 2107, "Derecho", true, false),
            new(2270, 6, 2108, "Contabilidad y auditoría", true, false),
            new(2271, 6, 2108, "Gestión financiera", true, false),
            new(2272, 6, 2108, "Administración", true, false),
            new(2273, 6, 2108, "Mercadotecnia y publicidad", true, false),
            new(2274, 6, 2108, "Información gerencial", true, false),
            new(2275, 6, 2108, "Comercio", true, false),
            new(2276, 6, 2108, "Competencias laborales", true, false),
            new(2280, 6, 2109, "Biología", true, false),
            new(2281, 6, 2109, "Biofísica", true, false),
            new(2282, 6, 2109, "Biofarmacéutica", true, false),
            new(2283, 6, 2109, "Biomedicina", true, false),
            new(2284, 6, 2109, "Bioquímica", true, false),
            new(2285, 6, 2109, "Genética", true, false),
            new(2286, 6, 2109, "Biodiversidad", true, false),
            new(2287, 6, 2109, "Neurociencias", true, false),
            new(2290, 6, 2110, "Medio ambiente", true, false),
            new(2291, 6, 2110, "Recursos Naturales Renovables", true, false),
            new(2300, 6, 2111, "Química", true, false),
            new(2301, 6, 2111, "Ciencias de la Tierra", true, false),
            new(2302, 6, 2111, "Física", true, false),
            new(2303, 6, 2111, "Ciencias Marítimas", true, false),
            new(2304, 6, 2111, "Ciencias Marinas", true, false),
            new(2310, 6, 2112, "Matemáticas", true, false),
            new(2311, 6, 2112, "Estadísticas", true, false),
            new(2312, 6, 2112, "Logística y transporte", true, false),
            new(2320, 6, 2113, "Computación", true, false),
            new(2321, 6, 2113, "Diseño y administración de redes y bases de datos", true, false),
            new(2322, 6, 2113, "Desarrollo y análisis de software y aplicaciones", true, false),
            new(2323, 6, 2113, "Sistemas de Información", true, false),
            new(2330, 6, 2114, "Química aplicada", true, false),
            new(2331, 6, 2114, "Tecnología de protección del medio ambiente", true, false),
            new(2332, 6, 2114, "Electricidad y energía", true, false),
            new(2333, 6, 2114, "Electrónica, automatización y sonido", true, false),
            new(2334, 6, 2114, "Mecánica y profesiones afines a la metalistería", true, false),
            new(2335, 6, 2114, "Diseño y construcción de vehículos, barcos y aeronaves motorizadas", true, false),
            new(2336, 6, 2114, "Tecnologías Nucleares y Energéticas", true, false),
            new(2337, 6, 2114, "Mecatrónica", true, false),
            new(2338, 6, 2114, "Hidráulica", true, false),
            new(2339, 6, 2114, "Telecomunicaciones", true, false),
            new(2340, 6, 2114, "Nanotecnología", true, false),
            new(2350, 6, 2115, "Procesamiento de alimentos", true, false),
            new(2351, 6, 2115, "Materiales", true, false),
            new(2352, 6, 2115, "Productos textiles", true, false),
            new(2353, 6, 2115, "Minería y extracción", true, false),
            new(2354, 6, 2115, "Producción industrial", true, false),
            new(2355, 6, 2115, "Seguridad industrial", true, false),
            new(2356, 6, 2115, "Diseño industrial y de procesos", true, false),
            new(2357, 6, 2115, "Mantenimiento industrial", true, false),
            new(2360, 6, 2116, "Arquitectura, urbanismo y restauración", true, false),
            new(2361, 6, 2116, "Construcción e ingeniería civil", true, false),
            new(2370, 6, 2117, "Producción agrícola y ganadera", true, false),
            new(2371, 6, 2118, "Silvicultura", true, false),
            new(2372, 6, 2119, "Pesca", true, false),
            new(2373, 6, 2120, "Veterinaria", true, false),
            new(2380, 6, 2121, "Odontología", true, false),
            new(2381, 6, 2121, "Medicina", true, false),
            new(2382, 6, 2121, "Enfermería y obstetricia", true, false),
            new(2383, 6, 2121, "Tecnología de diagnóstico y tratamiento médico", true, false),
            new(2384, 6, 2121, "Terapia, Rehabilitación y Tratamiento de la Salud", true, false),
            new(2385, 6, 2121, "Farmacia", true, false),
            new(2386, 6, 2121, "Terapias alternativas y complementarias", true, false),
            new(2387, 6, 2121, "Salud Pública", true, false),
            new(2390, 6, 2122, "Asistencia a adultos mayores y discapacitados", true, false),
            new(2391, 6, 2122, "Asistencia a la infancia y servicios para jóvenes", true, false),
            new(2400, 6, 2123, "Peluquería y tratamiento de belleza", true, false),
            new(2401, 6, 2123, "Hotelería y gastronomía", true, false),
            new(2402, 6, 2123, "Actividad física", true, false),
            new(2403, 6, 2123, "Turismo", true, false),
            new(2410, 6, 2124, "Prevención y gestión de riesgos", true, false),
            new(2411, 6, 2124, "Salud y seguridad ocupacional", true, false),
            new(2420, 6, 2125, "Educación policial, militar y defensa", true, false),
            new(2421, 6, 2125, "Seguridad ciudadana", true, false),
            new(2430, 6, 2126, "Gestión del transporte", true, false),
            new(2431, 7, null, "Nacional", true, false),
            new(2432, 7, null, "Provincial", true, false),
            new(2433, 7, null, "Cantonal2", true, false),
            new(2434, 7, null, "Parroquial", true, false),
            new(2435, 7, null, "Institucional", true, false),
            new(2436, 7, null, "Internacional", true, false),
        ]),
        new ProjectsSeedTable<FundingType, FundingTypesRow>("FundingTypes", [
            new(1, "Externo", true, false),
            new(2, "Interno", true, false),
            new(3, "Propio", true, false),
            new(4, "Sin financiamiento", true, false),
        ]),
        new ProjectsSeedTable<MemberRoleType, MemberRoleTypesRow>("MemberRoleTypes", [
            new(1, "Coordinador Principal", true, 1, true),
            new(2, "Coordinador Subrogante", true, 1, true),
            new(3, "Investigador", true, 1, false),
            new(4, "Investigador", true, 2, false),
        ]),
        new ProjectsSeedTable<Country, CountriesRow>("Countries", [
            new(1, "Ecuador", "EC", "ECU", true, false),
            new(2, "Argentina", "AR", "ARG", true, false),
            new(3, "Bolivia", "BO", "BOL", true, false),
            new(4, "Brasil", "BR", "BRA", true, false),
            new(5, "Chile", "CL", "CHL", true, false),
            new(6, "Colombia", "CO", "COL", true, false),
            new(7, "Paraguay", "PY", "PRY", true, false),
            new(8, "Peru", "PE", "PER", true, false),
            new(9, "Uruguay", "UY", "URY", true, false),
            new(10, "Venezuela", "VE", "VEN", true, false),
            new(11, "México", "MX", "MEX", true, false),
            new(12, "Guatemala", "GT", "GTM", true, false),
            new(13, "El Salvador", "SV", "SLV", true, false),
            new(14, "Honduras", "HN", "HND", true, false),
            new(15, "Nicaragua", "NI", "NIC", true, false),
            new(16, "Costa Rica", "CR", "CRI", true, false),
            new(17, "Panamá", "PA", "PAN", true, false),
            new(18, "Cuba", "CU", "CUB", true, false),
            new(19, "Dominicana", "DO", "DOM", true, false),
            new(20, "Haití", "HT", "HTI", true, false),
            new(21, "Estados Unidos", "US", "USA", true, false),
            new(22, "Canadá", "CA", "CAN", true, false),
            new(23, "España", "ES", "ESP", true, false),
            new(24, "Alemania", "DE", "DEU", true, false),
            new(25, "Francia", "FR", "FRA", true, false),
            new(26, "Italia", "IT", "ITA", true, false),
            new(27, "Reino Unido", "GB", "GBR", true, false),
            new(28, "Portugal", "PT", "PRT", true, false),
            new(29, "Países Bajos", "NL", "NLD", true, false),
            new(30, "Suiza", "CH", "CHE", true, false),
            new(31, "China", "CN", "CHN", true, false),
            new(32, "Japón", "JP", "JPN", true, false),
            new(33, "Corea del Sur", "KR", "KOR", true, false),
            new(34, "India", "IN", "IND", true, false),
            new(35, "Singapur", "SG", "SGP", true, false),
            new(36, "Australia", "AU", "AUS", true, false),
            new(37, "Nueva Zelanda", "NZ", "NZL", true, false),
            new(38, "Sudáfrica", "ZA", "ZAF", true, false),
            new(39, "Egipto", "EG", "EGY", true, false),
            new(40, "Marruecos", "MA", "MAR", true, false),
            new(41, "NO VALIDO", "N/A", "N/A", true, true),
        ]),
        new ProjectsSeedTable<Institution, InstitutionsRow>("Institutions", [
            new(1, "UNIVERSIDAD TECNICA DE MACHALA", 1, true, false),
            new(2, "UNIVERSIDAD ESTATAL DE BOLIVAR", 1, true, false),
            new(3, "UNIVERSIDAD DE CUENCA", 1, true, false),
            new(4, "UNIVERSIDAD CENTRAL DEL ECUADOR", 1, true, false),
            new(5, "UNIVERSIDAD DE GUAYAQUIL", 1, true, false),
            new(6, "ESCUELA POLITECNICA NACIONAL", 1, true, false),
            new(7, "ESCUELA SUPERIOR POLITECNICA DEL LITORAL (ESPOL)", 1, true, false),
            new(8, "UNIVERSIDAD DE LAS FUERZAS ARMADAS (ESPE)", 1, true, false),
            new(9, "UNIVERSIDAD LAICA ELOY ALFARO DE MANABI", 1, true, false),
            new(10, "UNIVERSIDAD TECNICA DEL NORTE", 1, true, false),
            new(11, "UNIVERSIDAD ESTATAL DE MILAGRO", 1, true, false),
            new(12, "UNIVERSIDAD NACIONAL DE LOJA", 1, true, false),
            new(13, "UNIVERSIDAD CATOLICA DE SANTIAGO DE GUAYAQUIL", 1, true, false),
            new(14, "UNIVERSIDAD POLITECNICA SALESIANA", 1, true, false),
            new(15, "UNIVERSIDAD ANDINA SIMON BOLIVAR", 1, true, false),
            new(16, "UNIVERSIDAD TECNOLOGICA EQUINOCCIAL (UTE)", 1, true, false),
            new(17, "UNIVERSIDAD SAN FRANCISCO DE QUITO (USFQ)", 1, true, false),
            new(18, "UNIVERSIDAD INTERNACIONAL DEL ECUADOR (UIDE)", 1, true, false),
            new(19, "UNIVERSIDAD CASA GRANDE", 1, true, false),
            new(20, "UNIVERSIDAD DE ESPECIALIDADES ESPIRITU SANTO (UEES)", 1, true, false),
            new(21, "UNIVERSIDAD ESTATAL PENINSULA DE SANTA ELENA", 1, true, false),
            new(22, "UNIVERSIDAD LUIS VARGAS TORRES DE ESMERALDAS", 1, true, false),
            new(23, "UNIVERSIDAD TECNICA ESTATAL DE QUEVEDO", 1, true, false),
            new(24, "UNIVERSIDAD ESTATAL AMAZONICA", 1, true, false),
            new(25, "UNIVERSIDAD REGIONAL AUTONOMA DE LOS ANDES (UNIANDES)", 1, true, false),
            new(26, "UNIVERSIDAD METROPOLITANA", 1, true, false),
            new(27, "UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO (UNAM)", 11, true, false),
            new(28, "INSTITUTO TECNOLOGICO Y DE ESTUDIOS SUPERIORES DE MONTERREY (TEC DE MONTERREY)", 11, true, false),
            new(29, "UNIVERSIDAD DE BUENOS AIRES (UBA)", 2, true, false),
            new(30, "UNIVERSIDAD NACIONAL DE LA PLATA (UNLP)", 2, true, false),
            new(31, "UNIVERSIDAD DE CHILE", 5, true, false),
            new(32, "PONTIFICIA UNIVERSIDAD CATOLICA DE CHILE", 5, true, false),
            new(33, "UNIVERSIDAD NACIONAL DE COLOMBIA", 6, true, false),
            new(34, "UNIVERSIDAD DE LOS ANDES (COLOMBIA)", 6, true, false),
            new(35, "UNIVERSIDAD DE SAO PAULO (USP)", 4, true, false),
            new(36, "UNIVERSIDADE ESTADUAL DE CAMPINAS (UNICAMP)", 4, true, false),
            new(37, "NO VALIDO", 41, true, true),
        ]),
        new ProjectsSeedTable<ExternalResearcher, ExternalResearchersRow>("ExternalResearchers", [
            new(1, "AGREGAR MANUALMENTE", "correo@example.com", "0999999999", 37),
        ]),
        new ProjectsSeedTable<ProjectExtensionType, ProjectExtensionTypesRow>("ProjectExtensionTypes", [
            new(1, "Por objetivos", true, false),
            new(2, "Por ampliación de plazo", true, false),
        ]),
        new ProjectsSeedTable<ProjectOriginType, ProjectOriginTypesRow>("ProjectOriginTypes", [
            new(1, "Interno", true, true),
            new(2, "Extern0", true, true),
            new(3, "Mixto", true, true),
        ]),
        new ProjectsSeedTable<ExportField, ExportFieldsRow>("ExportFields", [
            new(1, "PROJECT_CODE", "Código de proyecto", "PROJECT_CODE", "Código interno del proyecto (p.ej. PII-2025-001).", "ProjectFlatReportDTO", "ProjectCode", true),
            new(2, "PROJECT_NAME", "Nombre del proyecto", "PROJECT_NAME", "Título o nombre oficial del proyecto.", "ProjectFlatReportDTO", "ProjectName", true),
            new(3, "PROJECT_NUMBER", "Número de proyecto", "PROJECT_NUMBER", "Número secuencial/correlativo del proyecto.", "ProjectFlatReportDTO", "ProjectNumber", true),
            new(4, "PROJECT_TYPE", "Tipo de proyecto", "PROJECT_TYPE", "Tipo de proyecto (formación, investigación, vinculación, etc.).", "ProjectFlatReportDTO", "ProjectTypeName", true),
            new(5, "PROJECT_STATE", "Estado del proyecto", "PROJECT_STATE", "Estado actual del proyecto (En ejecución, Finalizado, etc.).", "ProjectFlatReportDTO", "ProjectStateName", true),
            new(6, "CONVOCATION_NAME", "Convocatoria", "CONVOCATION", "Convocatoria o línea de financiamiento del proyecto.", "ProjectFlatReportDTO", "ConvocationName", true),
            new(7, "APPROVAL_DATE", "Fecha de aprobación", "APPROVAL_DATE", "Fecha de aprobación del proyecto.", "ProjectFlatReportDTO", "ApprovalDate", true),
            new(8, "START_DATE", "Fecha de inicio", "START_DATE", "Fecha de inicio del proyecto.", "ProjectFlatReportDTO", "StartDate", true),
            new(9, "DURATION_MONTHS", "Duración (meses)", "DURATION_MONTHS", "Duración total del proyecto en meses.", "ProjectFlatReportDTO", "DurationInMonths", true),
            new(10, "TENTATIVE_END_DATE", "Fecha tentativa de fin", "TENTATIVE_END_DATE", "Fecha tentativa de finalización del proyecto.", "ProjectFlatReportDTO", "TentativeEndDate", true),
            new(11, "REAL_END_DATE", "Fecha real de fin", "REAL_END_DATE", "Fecha real de finalización del proyecto (si existe).", "ProjectFlatReportDTO", "RealEndDate", true),
            new(12, "EXECUTION_PERCENTAGE", "% de ejecución", "EXECUTION_PERCENT", "Porcentaje global de ejecución del proyecto.", "ProjectFlatReportDTO", "ExecutionPercentage", true),
            new(13, "FACULTY_NAME", "Facultad", "FACULTY", "Facultad responsable del proyecto (según directorio externo).", "ProjectFlatReportDTO", "FacultyName", true),
            new(14, "COORDINATOR_NAME", "Coordinador del proyecto", "COORDINATOR_NAME", "Nombre del coordinador/director del proyecto.", "ProjectFlatReportDTO", "CoordinatorName", true),
            new(15, "COORDINATOR_EMAIL", "Correo del coordinador", "COORDINATOR_EMAIL", "Correo electrónico del coordinador del proyecto.", "ProjectFlatReportDTO", "CoordinatorEmail", true),
            new(16, "COORDINATOR_PHONE", "Teléfono del coordinador", "COORDINATOR_PHONE", "Teléfono de contacto del coordinador del proyecto.", "ProjectFlatReportDTO", "CoordinatorPhone", true),
            new(28, "SUBROGANT_NAME", "Subrogante del proyecto", "SUBROGANT_NAME", "Nombre del coordinador subrogante del proyecto.", "ProjectFlatReportDTO", "SubrogantName", true),
            new(29, "SUBROGANT_EMAIL", "Correo del subrogante", "SUBROGANT_EMAIL", "Correo electrónico del coordinador subrogante del proyecto.", "ProjectFlatReportDTO", "SubrogantEmail", true),
            new(30, "SUBROGANT_PHONE", "Teléfono del subrogante", "SUBROGANT_PHONE", "Teléfono de contacto del coordinador subrogante del proyecto.", "ProjectFlatReportDTO", "SubrogantPhone", true),
            new(17, "SENESCYT_MEMBERS", "Investigadores SENESCYT", "SENESCYT_MEMBERS", "Lista de investigadores acreditados SENESCYT vinculados al proyecto (concatenados).", "ProjectFlatReportDTO", "SenescytMembers", true),
            new(18, "EXTERNAL_RESEARCHER_NAMES", "Investigadores externos", "EXTERNAL_NAMES", "Nombres de investigadores externos asociados al proyecto.", "ProjectFlatReportDTO", "ExternalResearchers", true),
            new(19, "EXTERNAL_INSTITUTIONS", "Instituciones de investigadores externos", "EXTERNAL_INSTITUTIONS", "Instituciones asociadas a los investigadores externos del proyecto.", "ProjectFlatReportDTO", "ExternalResearchers", true),
            new(20, "BUDGET_INITIAL_SUMMARY", "Presupuesto inicial (resumen)", "BUDGET_INITIAL", "Resumen de montos iniciales de presupuesto del proyecto (concatenados).", "ProjectFlatReportDTO", "Budgets", true),
            new(21, "BUDGET_FUNDINGTYPES_SUMMARY", "Tipos de financiamiento", "BUDGET_FUNDING_TYPES", "Resumen de tipos de financiamiento asociados al presupuesto del proyecto.", "ProjectFlatReportDTO", "Budgets", true),
            new(22, "BUDGET_CERTIFIED_SUMMARY", "Presupuesto certificado (resumen)", "BUDGET_CERTIFIED", "Resumen de montos certificados del presupuesto del proyecto.", "ProjectFlatReportDTO", "Budgets", true),
            new(23, "BUDGET_EXECUTED_SUMMARY", "Presupuesto ejecutado (resumen)", "BUDGET_EXECUTED", "Resumen de montos ejecutados del presupuesto del proyecto.", "ProjectFlatReportDTO", "Budgets", true),
            new(24, "PRODUCT_TITLES_SUMMARY", "Productos (títulos)", "PRODUCT_TITLES", "Títulos de los productos asociados al proyecto (concatenados).", "ProjectFlatReportDTO", "Products", true),
            new(25, "PRODUCT_TYPES_SUMMARY", "Productos (tipos)", "PRODUCT_TYPES", "Tipos de productos asociados al proyecto (concatenados).", "ProjectFlatReportDTO", "Products", true),
            new(26, "MATRIX_DYNAMIC_OBJECTIVES", "Objetivos del proyecto (bundle)", "MATRIX_DYNAMIC_OBJECTIVES", "Conjunto de objetivos del proyecto. Se expande a columnas específicas (objetivo general y objetivos específicos) según la plantilla.", "ProjectFlatReportDTO", "Objectives", true),
            new(27, "MATRIX_DYNAMIC_CATEGORIES", "Categorías de investigación (bundle)", "MATRIX_DYNAMIC_CATEGORIES", "Conjunto de categorías de investigación asociadas al proyecto (dominio, línea, campos). Se expande a columnas específicas según la plantilla.", "ProjectFlatReportDTO", "ResearchCategories", true),
        ]),
        new ProjectsSeedTable<ExportTemplate, ExportTemplatesRow>("ExportTemplates", [
            new(1, "TD", "TODO", "CASES", "v1", false, true),
        ]),
        new ProjectsSeedTable<ExportTemplateColumn, ExportTemplateColumnsRow>("ExportTemplateColumns", [
            new(1, 1, 6, "CONVOCATION", 1, true, null, null),
            new(2, 1, 1, "PROJECT_CODE", 2, true, null, null),
            new(3, 1, 3, "PROJECT_NUMBER", 3, true, null, null),
            new(4, 1, 2, "PROJECT_NAME", 4, true, null, null),
            new(5, 1, 13, "FACULTY", 5, true, null, null),
            new(6, 1, 12, "EXECUTION_PERCENT", 6, true, null, null),
            new(7, 1, 7, "APPROVAL_DATE", 7, true, null, null),
            new(8, 1, 8, "START_DATE", 8, true, null, null),
            new(9, 1, 10, "TENTATIVE_END_DATE", 9, true, null, null),
            new(10, 1, 11, "REAL_END_DATE", 10, true, null, null),
            new(11, 1, 4, "PROJECT_TYPE", 11, true, null, null),
            new(12, 1, 5, "PROJECT_STATE", 12, true, null, null),
            new(13, 1, 14, "COORDINATOR_NAME", 13, true, null, null),
            new(14, 1, 15, "COORDINATOR_EMAIL", 14, true, null, null),
            new(15, 1, 16, "COORDINATOR_PHONE", 15, true, null, null),
            new(16, 1, 28, "SUBROGANT_NAME", 16, true, null, null),
            new(17, 1, 29, "SUBROGANT_EMAIL", 17, true, null, null),
            new(18, 1, 30, "SUBROGANT_PHONE", 18, true, null, null),
            new(19, 1, 19, "EXTERNAL_INSTITUTIONS", 19, true, null, null),
            new(20, 1, 18, "EXTERNAL_NAMES", 20, true, null, null),
            new(21, 1, 17, "SENESCYT_MEMBERS", 21, true, null, null),
            new(22, 1, 9, "DURATION_MONTHS", 22, true, null, null),
            new(23, 1, 21, "BUDGET_FUNDING_TYPES", 23, true, null, null),
            new(24, 1, 20, "BUDGET_INITIAL", 24, true, null, null),
            new(25, 1, 22, "BUDGET_CERTIFIED", 25, true, null, null),
            new(26, 1, 22, "BUDGET_CERTIFIED", 26, true, null, null),
            new(27, 1, 26, "OBJETIVOS_BUNDLE", 27, true, null, null),
            new(28, 1, 27, "RESEARCH_CATEGORIES_BUNDLE", 28, true, null, null),
            new(29, 1, 25, "PRODUCT_TYPES", 29, true, null, null),
            new(30, 1, 24, "PRODUCT_TITLES", 30, true, null, null),
        ]),
        new ProjectsSeedTable<ProductType, ProductTypesRow>("ProductTypes", [
            new(1, "PRODUCCIÓN CIENTÍFICA", true, false),
            new(2, "PRODUCCIÓN REGIONAL", true, false),
            new(3, "PONENCIAS", true, false),
            new(4, "LIBROS", true, false),
            new(5, "CAPÍTULO DE LIBROS", true, false),
            new(6, "TRABAJO DE TITULACIÓN", true, false),
            new(7, "AYUDANTE / BECARIO / PRÁCTICAS PREPROFESIONALES", true, false),
        ]),
        new ProjectsSeedTable<ProductAttribute, ProductAttributesRow>("ProductAttributes", [
            new(1, 0, null, "TÍTULO", true, false),
            new(2, 0, null, "AUTORES", true, false),
            new(3, 0, null, "REVISTA", true, false),
            new(4, 0, null, "BASE DE DATOS", true, false),
            new(5, 1, null, "IMPACTO / SJR", true, false),
            new(6, 0, null, "CUARTIL", true, false),
            new(7, 0, null, "ISSN / ISBN", true, false),
            new(8, 0, null, "DOI", true, false),
            new(9, 1, null, "AÑO", true, false),
            new(10, 3, null, "URL A LA FECHA DE CONSULTA", true, false),
            new(11, 0, null, "NOMBRE DEL EVENTO", true, false),
            new(12, 2, null, "FECHA", true, false),
            new(13, 0, null, "PAÍS", true, false),
            new(14, 0, null, "EDITORIAL", true, false),
            new(15, 0, null, "CAPÍTULO DEL LIBRO", true, false),
            new(16, 0, null, "ESTUDIANTE", true, false),
            new(17, 0, null, "GRADO / POSGRADO", true, false),
            new(18, 0, null, "RESOLUCIÓN", true, false),
            new(19, 0, null, "ACTIVIDADES EJECUTADAS", true, false),
        ]),
        new ProjectsSeedTable<ProductAttributeDefinition, ProductAttributeDefinitionsRow>("ProductAttributeDefinitions", [
            new(1, 1, 1, false, 1),
            new(2, 1, 2, false, 2),
            new(3, 1, 3, false, 3),
            new(4, 1, 4, false, 4),
            new(5, 1, 5, false, 5),
            new(6, 1, 6, false, 6),
            new(7, 1, 7, false, 7),
            new(8, 1, 8, false, 8),
            new(9, 1, 9, false, 9),
            new(10, 1, 10, false, 10),
            new(11, 2, 1, false, 1),
            new(12, 2, 2, false, 2),
            new(13, 2, 3, false, 3),
            new(14, 2, 4, false, 4),
            new(15, 2, 7, false, 5),
            new(16, 2, 10, false, 6),
            new(17, 3, 1, false, 1),
            new(18, 3, 11, false, 2),
            new(19, 3, 12, false, 3),
            new(20, 3, 13, false, 4),
            new(21, 4, 1, false, 1),
            new(22, 4, 2, false, 2),
            new(23, 4, 9, false, 3),
            new(24, 4, 13, false, 4),
            new(25, 4, 14, false, 5),
            new(26, 4, 7, false, 6),
            new(27, 5, 1, false, 1),
            new(28, 5, 15, false, 2),
            new(29, 5, 2, false, 3),
            new(30, 5, 9, false, 4),
            new(31, 5, 13, false, 5),
            new(32, 5, 14, false, 6),
            new(33, 5, 7, false, 7),
            new(34, 6, 16, false, 1),
            new(35, 6, 17, false, 2),
            new(36, 6, 18, false, 3),
            new(37, 7, 16, false, 1),
            new(38, 7, 19, false, 2),
            new(39, 7, 18, false, 3),
        ]),
    ];
}

internal sealed record DocumentTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record GroupTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ConvocationsRow(int Id, string Name, string? Code, bool IsActive, bool IsLocked);

internal sealed record ProjectStatesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ProjectTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record TransactionTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record VisitStatesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ObjectiveTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ResearchCategoryGroupsRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ResearchCategoryTypesRow(int Id, string Name, int ResearchCategoryGroupId, bool IsActive, bool IsFilterEnabled, bool IsLocked);

internal sealed record ResearchCategoriesRow(int Id, int ResearchCategoryTypeId, int? ParentCategoryId, string Name, bool IsActive, bool IsLocked);

internal sealed record FundingTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record MemberRoleTypesRow(int Id, string Name, bool IsActive, int Flag, bool IsLocked);

internal sealed record CountriesRow(int Id, string Name, string IsoCode, string IsoAlpha3, bool IsActive, bool IsLocked);

internal sealed record InstitutionsRow(int Id, string Name, int CountryId, bool IsActive, bool IsLocked);

internal sealed record ExternalResearchersRow(int ExternalResearcherId, string FullName, string Email, string PhoneNumber, int InstitutionId);

internal sealed record ProjectExtensionTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ProjectOriginTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ExportFieldsRow(int Id, string Key, string DisplayName, string DefaultHeader, string Description, string SourceEntity, string SourcePath, bool IsActive);

internal sealed record ExportTemplatesRow(int Id, string Key, string Name, string TargetSystem, string Version, bool IsDefault, bool IsActive);

internal sealed record ExportTemplateColumnsRow(int Id, int TemplateId, int ExportFieldId, string TargetHeader, int OrderIndex, bool IsRequired, string? Format, string? Separator);

internal sealed record ProductTypesRow(int Id, string Name, bool IsActive, bool IsLocked);

internal sealed record ProductAttributesRow(int Id, int DataType, string? Unit, string Name, bool IsActive, bool IsLocked);

internal sealed record ProductAttributeDefinitionsRow(int Id, int ProductTypeId, int ProductAttributeId, bool IsRequired, int DisplayOrder);
