// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tesisproject.backend.Data;

#nullable disable

namespace tesisproject.backend.Migrations.ArticlesDw
{
    [DbContext(typeof(ArticlesDwContext))]
    partial class ArticlesDwContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ArticlesDW")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAcademicTerm", b =>
                {
                    b.Property<int>("AcademicTermKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicTermKey"));

                    b.Property<int>("AcademicTermId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AcademicTermKey");

                    b.HasIndex("AcademicTermId")
                        .IsUnique();

                    b.ToTable("DimAcademicTerms", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimArticle", b =>
                {
                    b.Property<int>("ArticleKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleKey"));

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Doi")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Filiacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IssnIsbn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Proceedings")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProceedingsName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PublicationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<short?>("PublicationYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("YearRaw")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ArticleKey");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.ToTable("DimArticles", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAuthor", b =>
                {
                    b.Property<int>("AuthorKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorKey"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalFullName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ExternalResearcherId")
                        .HasColumnType("int");

                    b.Property<int?>("IdAsp")
                        .HasColumnType("int");

                    b.Property<bool>("IsInstitutional")
                        .HasColumnType("bit");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuthorKey");

                    b.HasIndex("AppUserId");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.HasIndex("ExternalResearcherId");

                    b.HasIndex("IdAsp");

                    b.HasIndex("IsInstitutional");

                    b.ToTable("DimAuthors", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PeriodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DateKey");

                    b.HasIndex("Date");

                    b.HasIndex("Year", "Month");

                    b.ToTable("DimDates", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", b =>
                {
                    b.Property<int>("FacultyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyKey"));

                    b.Property<string>("FacultyCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("FacultyName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FacultyKey");

                    b.HasIndex("FacultyCode");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FacultyName");

                    b.ToTable("DimFaculties", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimField", b =>
                {
                    b.Property<int>("FieldKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldKey"));

                    b.Property<int>("BroadFieldId")
                        .HasColumnType("int");

                    b.Property<string>("BroadFieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DetailedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("DetailedFieldName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SpecificFieldId")
                        .HasColumnType("int");

                    b.Property<string>("SpecificFieldName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("FieldKey");

                    b.HasIndex("BroadFieldId", "SpecificFieldId", "DetailedFieldId")
                        .IsUnique()
                        .HasFilter("[SpecificFieldId] IS NOT NULL AND [DetailedFieldId] IS NOT NULL");

                    b.ToTable("DimFields", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingDatabase", b =>
                {
                    b.Property<int>("IndexingDatabaseKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexingDatabaseKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IndexingDatabaseKey");

                    b.HasIndex("Name");

                    b.ToTable("DimIndexingDatabases", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingSource", b =>
                {
                    b.Property<int>("IndexingSourceKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexingSourceKey"));

                    b.Property<int>("IndexingSourceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IndexingSourceKey");

                    b.HasIndex("IndexingSourceId")
                        .IsUnique();

                    b.ToTable("DimIndexingSources", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimJournal", b =>
                {
                    b.Property<int>("JournalKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JournalKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JournalKey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DimJournals", "ArticlesDW", t =>
                        {
                            t.HasCheckConstraint("CK_DimJournals_Name_Trimmed", "[Name] <> N'' AND [Name] = LTRIM(RTRIM([Name]))");
                        });
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProductType", b =>
                {
                    b.Property<int>("ProductTypeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductTypeKey"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductTypeKey");

                    b.HasIndex("Name");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("DimProductTypes", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimPublicationStatus", b =>
                {
                    b.Property<int>("PublicationStatusKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicationStatusKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("PublicationStatusId")
                        .HasColumnType("tinyint");

                    b.HasKey("PublicationStatusKey");

                    b.HasIndex("PublicationStatusId")
                        .IsUnique();

                    b.ToTable("DimPublicationStatuses", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimQuartile", b =>
                {
                    b.Property<int>("QuartileKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuartileKey"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuartileKey");

                    b.HasIndex("Code");

                    b.ToTable("DimQuartiles", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimResearchLine", b =>
                {
                    b.Property<int>("ResearchLineKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchLineKey"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ResearchLineId")
                        .HasColumnType("int");

                    b.HasKey("ResearchLineKey");

                    b.HasIndex("ResearchLineId")
                        .IsUnique();

                    b.ToTable("DimResearchLines", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimVenue", b =>
                {
                    b.Property<int>("VenueKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueKey"));

                    b.Property<string>("IssnCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<string>("Volume")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VenueKey");

                    b.HasIndex("VenueId")
                        .IsUnique();

                    b.ToTable("DimVenues", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticleAuthor", b =>
                {
                    b.Property<int>("FactArticleAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactArticleAuthorId"));

                    b.Property<string>("AffiliationSnapshot")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("AuthorKey")
                        .HasColumnType("int");

                    b.Property<int?>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryAuthor")
                        .HasColumnType("bit");

                    b.Property<string>("NameSnapshot")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Participation")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ProductAuthorId")
                        .HasColumnType("int");

                    b.HasKey("FactArticleAuthorId");

                    b.HasIndex("AuthorKey");

                    b.HasIndex("ProductAuthorId")
                        .IsUnique();

                    b.HasIndex("ArticleKey", "AuthorKey")
                        .IsUnique();

                    b.ToTable("FactArticleAuthors", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticleIndexing", b =>
                {
                    b.Property<int>("FactArticleIndexingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactArticleIndexingId"));

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("IndexingSourceKey")
                        .HasColumnType("int");

                    b.HasKey("FactArticleIndexingId");

                    b.HasIndex("IndexingSourceKey");

                    b.HasIndex("ArticleKey", "IndexingSourceKey")
                        .IsUnique();

                    b.ToTable("FactArticleIndexings", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticlePublication", b =>
                {
                    b.Property<int>("FactArticlePublicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactArticlePublicationId"));

                    b.Property<int?>("AcademicTermKey")
                        .HasColumnType("int");

                    b.Property<int>("ArticleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("ArticleFacultyKey")
                        .HasColumnType("int");

                    b.Property<int>("ArticleKey")
                        .HasColumnType("int");

                    b.Property<int>("AuthorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CreatedDateKey")
                        .HasColumnType("int");

                    b.Property<int?>("FieldKey")
                        .HasColumnType("int");

                    b.Property<bool?>("HasInterculturalFlag")
                        .HasColumnType("bit");

                    b.Property<int>("IndexingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("IndexingDatabaseKey")
                        .HasColumnType("int");

                    b.Property<bool?>("IsOpenAccessFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProjectResultFlag")
                        .HasColumnType("bit");

                    b.Property<int?>("JournalKey")
                        .HasColumnType("int");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeKey")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectFacultyKey")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicationStatusKey")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedDateKey")
                        .HasColumnType("int");

                    b.Property<int?>("QuartileKey")
                        .HasColumnType("int");

                    b.Property<int?>("ResearchLineKey")
                        .HasColumnType("int");

                    b.Property<decimal?>("Sjr")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("VenueKey")
                        .HasColumnType("int");

                    b.HasKey("FactArticlePublicationId");

                    b.HasIndex("AcademicTermKey");

                    b.HasIndex("ArticleFacultyKey");

                    b.HasIndex("ArticleKey")
                        .IsUnique();

                    b.HasIndex("CreatedDateKey");

                    b.HasIndex("FieldKey");

                    b.HasIndex("IndexingDatabaseKey");

                    b.HasIndex("JournalKey");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductTypeKey");

                    b.HasIndex("ProjectFacultyKey");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PublicationStatusKey");

                    b.HasIndex("PublishedDateKey");

                    b.HasIndex("QuartileKey");

                    b.HasIndex("ResearchLineKey");

                    b.HasIndex("VenueKey");

                    b.ToTable("FactArticlePublications", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactVenueMetricYear", b =>
                {
                    b.Property<int>("FactVenueMetricYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactVenueMetricYearId"));

                    b.Property<string>("Quartile")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Sjr")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("VenueKey")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("FactVenueMetricYearId");

                    b.HasIndex("VenueKey", "Year")
                        .IsUnique();

                    b.ToTable("FactVenueMetricYears", "ArticlesDW");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticleAuthor", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAuthor", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticleIndexing", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingSource", "IndexingSource")
                        .WithMany()
                        .HasForeignKey("IndexingSourceKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("IndexingSource");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticlePublication", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimAcademicTerm", "AcademicTerm")
                        .WithMany()
                        .HasForeignKey("AcademicTermKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", "ArticleFaculty")
                        .WithMany()
                        .HasForeignKey("ArticleFacultyKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimArticle", "Article")
                        .WithOne()
                        .HasForeignKey("tesisproject.shared.Entities.Analytics.Dw.Facts.FactArticlePublication", "ArticleKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "CreatedDate")
                        .WithMany()
                        .HasForeignKey("CreatedDateKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimIndexingDatabase", "IndexingDatabase")
                        .WithMany()
                        .HasForeignKey("IndexingDatabaseKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimJournal", "Journal")
                        .WithMany()
                        .HasForeignKey("JournalKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimFaculty", "ProjectFaculty")
                        .WithMany()
                        .HasForeignKey("ProjectFacultyKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimPublicationStatus", "PublicationStatus")
                        .WithMany()
                        .HasForeignKey("PublicationStatusKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimDate", "PublishedDate")
                        .WithMany()
                        .HasForeignKey("PublishedDateKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimQuartile", "Quartile")
                        .WithMany()
                        .HasForeignKey("QuartileKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimResearchLine", "ResearchLine")
                        .WithMany()
                        .HasForeignKey("ResearchLineKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimVenue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueKey")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AcademicTerm");

                    b.Navigation("Article");

                    b.Navigation("ArticleFaculty");

                    b.Navigation("CreatedDate");

                    b.Navigation("Field");

                    b.Navigation("IndexingDatabase");

                    b.Navigation("Journal");

                    b.Navigation("ProductType");

                    b.Navigation("ProjectFaculty");

                    b.Navigation("PublicationStatus");

                    b.Navigation("PublishedDate");

                    b.Navigation("Quartile");

                    b.Navigation("ResearchLine");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Analytics.Dw.Facts.FactVenueMetricYear", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Analytics.Dw.Dimensions.DimVenue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueKey")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venue");
                });
#pragma warning restore 612, 618
        }
    }
}
