using tesisproject.backend.Data.UnifiedEntities.Articles;
using tesisproject.backend.Data.UnifiedEntities.Catalogs;
using tesisproject.backend.Services.Unified.Implementations.DataMigrations;

namespace tesisproject.backend.Services.Unified.DataMigrations.ArticlesInitialCatalog;

internal static class ArticlesCatalogSeedData
{
    public static IReadOnlyList<IArticlesCatalogSeedTable> Tables { get; } =
    [
        new ArticlesCatalogSeedTable<PublicationStatus, PublicationStatusRow>(
            "PublicationStatuses", nameof(PublicationStatusRow.PublicationStatusId),
            [
                new(1, "Registrado"),
                new(2, "Publicado"),
                new(3, "En revision"),
            ],
            [nameof(PublicationStatusRow.Name)]),
        new ArticlesCatalogSeedTable<ResearchLine, ResearchLineRow>(
            "ResearchLines", nameof(ResearchLineRow.ResearchLineId),
            [
                new(1, "Inteligencia Artificial"),
                new(2, "COMPORTAMIENTO SOCIAL Y EDUCATIVO"),
                new(3, "COMUNICACIÓN, SOCIEDAD, CULTURA Y TECNOLOGÍA"),
                new(4, "CONSTRUCCIÓN, ESTRUCTURAS, VÍAS Y TRANSPORTE"),
                new(5, "DESARROLLO EMPRESARIAL"),
                new(6, "DISEÑO, MATERIALES Y PRODUCCIÓN"),
                new(7, "ECONOMÍA DEL DESARROLLO"),
                new(8, "ENERGÍA, DESARROLLO SOSTENIBLE Y GESTIÓN DE RECURSOS NATURALES"),
                new(9, "EXCLUSION E INTEGRACION SOCIAL"),
                new(10, "MICROBIOLOGIA Y BIOTECNOLOGÍA"),
                new(11, "POLÍTICAS PÚBLICAS, DERECHO Y SOCIEDAD"),
                new(12, "PRODUCCIÓN AGROALIMENTARIA Y MEDIO AMBIENTE"),
                new(13, "SALUD HUMANA"),
                new(14, "SEGURIDAD Y SOBERANÍA ALIMENTARIA"),
                new(15, "TECNOLOGÍA DE LA INFORMACIÓN Y SISTEMAS DE CONTROL"),
                new(16, "NO APLICA"),
            ],
            [nameof(ResearchLineRow.Name)]),
        new ArticlesCatalogSeedTable<BroadField, BroadFieldRow>(
            "BroadFields", nameof(BroadFieldRow.BroadFieldId),
            [
                new(1, "Artes y humanidades"),
                new(2, "Ciencias sociales, periodismo, información y derecho"),
                new(3, "Administración"),
                new(4, "Ciencias naturales, matemáticas y estadística"),
                new(5, "Tecnologías de la información y la comunicación (TIC)"),
                new(6, "Ingeniería, industria y construcción"),
                new(7, "Agricultura, silvicultura, pesca y veterinaria"),
                new(8, "Salud y bienestar"),
                new(9, "Servicios"),
            ],
            [nameof(BroadFieldRow.Name)]),
        new ArticlesCatalogSeedTable<SpecificField, SpecificFieldRow>(
            "SpecificFields", nameof(SpecificFieldRow.SpecificFieldId),
            [
                new(1, 1, "ART", "Artes"),
                new(2, 1, "HUM", "Humanidades"),
                new(3, 1, "IDI", "Idiomas"),
                new(4, 2, "CSC", "Ciencias sociales y del comportamiento"),
                new(5, 2, "PER", "Periodismo e información"),
                new(6, 2, "DER", "Derecho"),
                new(7, 3, "ADM", "Educación comercial y administración"),
                new(8, 4, "BIO", "Ciencias biológicas y afines"),
                new(9, 4, "MEDAMB", "Medio ambiente"),
                new(10, 4, "FIS", "Ciencias físicas"),
                new(11, 4, "MAT", "Matemáticas y estadística"),
                new(12, 5, "TIC", "Tecnologías de la información y la comunicación"),
                new(13, 6, "ING", "Ingeniería y profesiones afines"),
                new(14, 6, "IND", "Industria y producción"),
                new(15, 6, "ARQ", "Arquitectura y construcción"),
                new(16, 7, "AGR", "Agricultura"),
                new(17, 7, "SIL", "Silvicultura"),
                new(18, 7, "PES", "Pesca"),
                new(19, 7, "VET", "Veterinaria"),
                new(20, 8, "SAL", "Salud"),
                new(21, 8, "BIE", "Bienestar"),
                new(22, 9, "SRVPER", "Servicios personales"),
                new(23, 9, "SRVPROT", "Servicios de protección"),
                new(24, 9, "SRVSEG", "Servicios de seguridad"),
                new(25, 9, "SRVTRANS", "Servicios de transporte"),
            ],
            [nameof(SpecificFieldRow.BroadFieldId), nameof(SpecificFieldRow.Code)],
            [nameof(SpecificFieldRow.BroadFieldId), nameof(SpecificFieldRow.Name)]),
        new ArticlesCatalogSeedTable<DetailedField, DetailedFieldRow>(
            "DetailedFields", nameof(DetailedFieldRow.DetailedFieldId),
            [
                new(1, 1, "1-12A", "Técnicas audiovisuales y producción para medios de comunicación"),
                new(2, 1, "2-12A", "Diseño"),
                new(3, 1, "3-12A", "Artes"),
                new(4, 1, "5-12A", "Música y artes escénicas"),
                new(5, 2, "1-22A", "Religión y teología"),
                new(6, 2, "2-22A", "Historia y arqueología"),
                new(7, 2, "3-22A", "Filosofía"),
                new(8, 3, "1-32A", "Idiomas"),
                new(9, 3, "2-32A", "Literatura y lingüística"),
                new(10, 4, "1-13A", "Economía"),
                new(11, 4, "81-13A", "Economía matemática"),
                new(12, 4, "2-13A", "Ciencias políticas"),
                new(13, 4, "3-13A", "Psicología"),
                new(14, 4, "4-13A", "Estudios sociales y culturales"),
                new(15, 4, "82-13A", "Estudios de género"),
                new(16, 4, "83-13A", "Geografía y territorio"),
                new(17, 5, "1-23A", "Periodismo y comunicación"),
                new(18, 5, "2-23A", "Bibliotecología, documentación y archivología"),
                new(19, 6, "1-33A", "Derecho"),
                new(20, 7, "1-14A", "Contabilidad y auditoría"),
                new(21, 7, "2-14A", "Gestión financiera"),
                new(22, 7, "3-14A", "Administración"),
                new(23, 7, "4-14A", "Mercadotecnia y publicidad"),
                new(24, 7, "5-14A", "Información gerencial"),
                new(25, 7, "6-14A", "Comercio"),
                new(26, 7, "7-14A", "Competencias laborales"),
                new(27, 8, "1-15A", "Biología"),
                new(28, 8, "81-15A", "Biofísica"),
                new(29, 8, "82-15A", "Biofarmacéutica"),
                new(30, 8, "83-15A", "Biomedicina"),
                new(31, 8, "2-15A", "Bioquímica"),
                new(32, 8, "84-15A", "Genética"),
                new(33, 8, "85-15A", "Biodiversidad"),
                new(34, 8, "86-15A", "Neurociencias"),
                new(35, 9, "1-25A", "Medio ambiente"),
                new(36, 9, "2-25A", "Recursos naturales renovables"),
                new(37, 10, "1-35A", "Química"),
                new(38, 10, "2-35A", "Ciencias de la Tierra"),
                new(39, 10, "3-35A", "Física"),
                new(40, 11, "1-45A", "Matemáticas"),
                new(41, 11, "2-45A", "Estadística"),
                new(42, 11, "81-45A", "Logística y transporte"),
                new(43, 12, "1-16A", "Computación"),
                new(44, 12, "2-16A", "Diseño y administración de redes y bases de datos"),
                new(45, 12, "3-16A", "Desarrollo y análisis de software y aplicaciones"),
                new(46, 12, "81-16A", "Sistemas de información"),
                new(47, 13, "1-17A", "Química aplicada"),
                new(48, 13, "2-17A", "Tecnología de protección del medio ambiente"),
                new(49, 13, "3-17A", "Electricidad y energía"),
                new(50, 13, "4-17A", "Electrónica, automatización y sonido"),
                new(51, 13, "5-17A", "Mecánica y profesiones afines"),
                new(52, 13, "6-17A", "Diseño y construcción de vehículos, barcos y aeronaves motorizadas"),
                new(53, 13, "81-17A", "Tecnologías nucleares y energéticas"),
                new(54, 13, "82-17A", "Mecatrónica"),
                new(55, 13, "83-17A", "Hidráulica"),
                new(56, 13, "84-17A", "Telecomunicaciones"),
                new(57, 13, "85-17A", "Nanotecnología"),
                new(58, 14, "1-27A", "Procesamiento de alimentos"),
                new(59, 14, "2-27A", "Materiales"),
                new(60, 14, "3-27A", "Productos textiles"),
                new(61, 14, "4-27A", "Minería y extracción"),
                new(62, 14, "5-27A", "Producción industrial"),
                new(63, 14, "6-27A", "Seguridad industrial"),
                new(64, 14, "7-27A", "Diseño industrial y de procesos"),
                new(65, 14, "82-27A", "Mantenimiento industrial"),
                new(66, 15, "1-37A", "Arquitectura, urbanismo y restauración"),
                new(67, 15, "2-37A", "Construcción e ingeniería civil"),
                new(68, 16, "1-18A", "Producción agrícola y ganadera"),
                new(69, 17, "1-28A", "Silvicultura"),
                new(70, 18, "1-38A", "Pesca"),
                new(71, 19, "1-48A", "Veterinaria"),
                new(72, 20, "1-19A", "Odontología"),
                new(73, 20, "2-19A", "Medicina"),
                new(74, 20, "3-19A", "Enfermería y obstetricia"),
                new(75, 20, "4-19A", "Tecnología de diagnóstico y tratamiento médico"),
                new(76, 20, "5-19A", "Terapia y rehabilitación"),
                new(77, 20, "6-19A", "Farmacia"),
                new(78, 20, "7-19A", "Terapias alternativas y complementarias"),
                new(79, 20, "8-19A", "Salud pública"),
                new(80, 21, "1-29A", "Asistencia a adultos mayores y discapacitados"),
                new(81, 21, "2-29A", "Asistencia a la infancia y servicios para jóvenes"),
                new(82, 22, "2-110A", "Peluquería y tratamiento de belleza"),
                new(83, 22, "3-110A", "Hotelería y gastronomía"),
                new(84, 22, "4-110A", "Actividad física"),
                new(85, 22, "5-110A", "Turismo"),
                new(86, 23, "1-210A", "Prevención y gestión de riesgos"),
                new(87, 23, "2-210A", "Salud y seguridad ocupacional"),
                new(88, 24, "1-310A", "Educación policial, militar y defensa"),
                new(89, 24, "2-310A", "Seguridad ciudadana"),
                new(90, 25, "1-410A", "Gestión del transporte"),
            ],
            [nameof(DetailedFieldRow.SpecificFieldId), nameof(DetailedFieldRow.Code)],
            [nameof(DetailedFieldRow.SpecificFieldId), nameof(DetailedFieldRow.Name)]),
        new ArticlesCatalogSeedTable<IndexingSource, IndexingSourceRow>(
            "IndexingSources", nameof(IndexingSourceRow.Id),
            [
                new(1, null, null, "Scopus", true, true),
                new(2, null, null, "Web of Science", true, true),
                new(3, null, null, "Latindex", true, true),
                new(4, null, null, "SciELO", true, true),
                new(5, null, null, "DOAJ", true, true),
                new(6, null, null, "Redalyc", true, true),
                new(7, null, null, "Dialnet", true, true),
                new(8, null, null, "ERIC", true, true),
            ],
            [nameof(IndexingSourceRow.Name)]),
    ];
}

internal sealed record PublicationStatusRow(byte PublicationStatusId, string Name);
internal sealed record ResearchLineRow(int ResearchLineId, string Name);
internal sealed record BroadFieldRow(int BroadFieldId, string Name);
internal sealed record SpecificFieldRow(int SpecificFieldId, int BroadFieldId, string? Code, string Name);
internal sealed record DetailedFieldRow(int DetailedFieldId, int SpecificFieldId, string? Code, string Name);
internal sealed record IndexingSourceRow(
    int Id,
    string? Abbreviation,
    string? ReferenceUrl,
    string Name,
    bool IsActive,
    bool IsLocked);
