using System.Globalization;
using tesisproject.backend.Data.UnifiedEntities.Articles;
using tesisproject.backend.Services.Unified.Implementations.DataMigrations;

namespace tesisproject.backend.Services.Unified.DataMigrations.ArticlesInitialCatalog;

internal static class ArticlesFormSeedData
{
    public static IReadOnlyList<IArticlesCatalogSeedTable> Tables { get; } =
    [
        new ArticlesCatalogSeedTable<FieldCatalogEntry, FieldCatalogRow>(
            "FieldCatalog", nameof(FieldCatalogRow.FieldId),
            [
                new(1, "Article", "Title", "Título", "string", "Physical",
                    "dbo.Articles", "Title", null,
                    true, false, true, true, true,
                    true, true, 1, 500, "Ingrese el título del artículo",
                    "Título principal del artículo científico", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(2, "Article", "Doi", "DOI", "string", "Physical",
                    "dbo.Articles", "Doi", null,
                    true, false, false, true, true,
                    true, true, 2, 200, "Ingrese el DOI",
                    "Identificador digital del artículo", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(3, "Article", "Year", "Año", "int", "Physical",
                    "dbo.Articles", "Year", null,
                    true, false, false, true, true,
                    true, true, 3, null, "Ingrese el año",
                    "Año de publicación", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(4, "Article", "PublishedAt", "Fecha de publicación", "datetime", "Physical",
                    "dbo.Articles", "PublishedAt", null,
                    true, false, false, true, true,
                    false, true, 4, null, null,
                    "Fecha exacta de publicación", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(5, "Article", "PageCount", "Número de páginas", "int", "Physical",
                    "dbo.Articles", "PageCount", null,
                    true, false, false, true, true,
                    false, true, 5, null, null,
                    "Cantidad de páginas del artículo", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(6, "Article", "PublicationUrl", "URL de publicación", "string", "Physical",
                    "dbo.Articles", "PublicationUrl", null,
                    true, false, false, true, true,
                    false, true, 6, 500, "https://...",
                    "Enlace del artículo", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(7, "Article", "IsOpenAccess", "Acceso abierto", "bool", "Physical",
                    "dbo.Articles", "IsOpenAccess", null,
                    true, false, false, true, true,
                    true, true, 7, null, null,
                    "Indica si el artículo es open access", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(8, "Article", "ExternalSource", "Fuente externa", "string", "Physical",
                    "dbo.Articles", "ExternalSource", null,
                    true, false, false, false, false,
                    false, true, 8, 50, null,
                    "Fuente de procedencia externa", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(9, "Article", "ExternalId", "Identificador externo", "string", "Physical",
                    "dbo.Articles", "ExternalId", null,
                    true, false, false, false, false,
                    false, true, 9, 150, null,
                    "Identificador del artículo en la fuente externa", null, null, Dt("2026-03-12T01:12:30.0875566"), null),
                new(10, "Article", "VenueId", "Revista / Venue", "fk", "CatalogReference",
                    "dbo.Articles", "VenueId", "dbo.Venues",
                    true, false, false, true, true,
                    true, true, 10, null, null,
                    "Revista o medio de publicación", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(11, "Article", "AcademicTermId", "Periodo académico", "fk", "CatalogReference",
                    "dbo.Articles", "AcademicTermId", "dbo.AcademicTerms",
                    true, false, false, true, true,
                    true, true, 11, null, null,
                    "Periodo académico asociado", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(12, "Article", "PublicationStatusId", "Estado de publicación", "fk", "CatalogReference",
                    "dbo.Articles", "PublicationStatusId", "dbo.PublicationStatuses",
                    true, false, false, true, true,
                    true, true, 12, null, null,
                    "Estado actual del artículo", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(13, "Article", "ResearchLineId", "Línea de investigación", "fk", "CatalogReference",
                    "dbo.Articles", "ResearchLineId", "dbo.ResearchLines",
                    true, false, false, true, true,
                    true, true, 13, null, null,
                    "Línea institucional asociada", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(14, "Article", "BroadFieldId", "Campo amplio", "fk", "CatalogReference",
                    "dbo.Articles", "BroadFieldId", "dbo.BroadFields",
                    true, false, false, true, true,
                    true, true, 14, null, null,
                    "Clasificación amplia del área", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(15, "Article", "SpecificFieldId", "Campo específico", "fk", "CatalogReference",
                    "dbo.Articles", "SpecificFieldId", "dbo.SpecificFields",
                    true, false, false, true, true,
                    true, true, 15, null, null,
                    "Clasificación específica del área", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(16, "Article", "DetailedFieldId", "Campo detallado", "fk", "CatalogReference",
                    "dbo.Articles", "DetailedFieldId", "dbo.DetailedFields",
                    true, false, false, true, true,
                    true, true, 16, null, null,
                    "Clasificación detallada del área", null, null, Dt("2026-03-12T01:15:16.0861469"), null),
                new(17, "ArticleParticipant", "Index", "Orden", "int", "Physical",
                    "dbo.ArticleParticipants", "Index", null,
                    true, false, true, true, true,
                    false, true, 1, null, null,
                    "Orden del autor dentro del artículo", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(18, "ArticleParticipant", "Identificacion", "Identificación", "string", "Physical",
                    "dbo.ArticleParticipants", "Identificacion", null,
                    true, false, true, true, true,
                    true, true, 2, 100, null,
                    "Número de identificación del participante", null, "{\"Rules\":[{\"Type\":\"numeric\"}]}", Dt("2026-03-12T01:16:43.6695971"), Dt("2026-06-02T09:31:50.1419653")),
                new(19, "ArticleParticipant", "Nombre", "Nombre completo", "string", "Physical",
                    "dbo.ArticleParticipants", "Nombre", null,
                    true, false, true, true, true,
                    true, true, 3, 300, null,
                    "Nombre del autor o coautor", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(20, "ArticleParticipant", "Participacion", "Participación", "string", "Physical",
                    "dbo.ArticleParticipants", "Participacion", null,
                    true, false, false, true, true,
                    false, true, 4, 150, null,
                    "Rol o participación dentro del artículo", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(21, "ArticleParticipant", "ParticipantType", "Tipo de participante", "string", "Physical",
                    "dbo.ArticleParticipants", "ParticipantType", null,
                    true, false, false, true, true,
                    true, true, 5, 50, null,
                    "Docente, estudiante, externo, etc.", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(22, "ArticleParticipant", "InstitutionalPersonId", "Persona institucional", "int", "Physical",
                    "dbo.ArticleParticipants", "InstitutionalPersonId", null,
                    true, false, false, false, false,
                    false, true, 6, null, null,
                    "Id futuro de docente o estudiante", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(23, "ArticleParticipant", "IsPrimaryAuthor", "Autor principal", "bool", "Physical",
                    "dbo.ArticleParticipants", "IsPrimaryAuthor", null,
                    true, false, false, true, true,
                    false, true, 7, null, null,
                    "Indica si es el autor principal", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(24, "ArticleParticipant", "Email", "Correo electrónico", "string", "Physical",
                    "dbo.ArticleParticipants", "Email", null,
                    true, false, false, true, true,
                    false, true, 8, 200, null,
                    "Correo del participante", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(25, "ArticleParticipant", "Orcid", "ORCID", "string", "Physical",
                    "dbo.ArticleParticipants", "Orcid", null,
                    true, false, false, true, true,
                    true, true, 9, 50, null,
                    "Código ORCID del autor", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(26, "ArticleParticipant", "Affiliation", "Afiliación", "string", "Physical",
                    "dbo.ArticleParticipants", "Affiliation", null,
                    true, false, false, true, true,
                    false, true, 10, 300, null,
                    "Institución o afiliación del participante", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(27, "ArticleParticipant", "ExternalAuthorId", "Identificador externo autor", "string", "Physical",
                    "dbo.ArticleParticipants", "ExternalAuthorId", null,
                    true, false, false, false, false,
                    false, true, 11, 150, null,
                    "Identificador externo del autor en APIs", null, null, Dt("2026-03-12T01:16:43.6695971"), null),
                new(28, "Article", "FundingCode", "Código de financiamiento", "string", "Dynamic",
                    null, null, null,
                    false, true, false, true, true,
                    true, true, 100, 100, "Ingrese el código de financiamiento",
                    "Campo dinámico para registrar el financiamiento del artículo", null, null, Dt("2026-03-12T01:55:31.7953332"), null),
                new(29, "Article", "PublisherCountry", "País de la editorial", "string", "Dynamic",
                    null, null, null,
                    false, true, false, true, true,
                    true, true, 101, 100, "Ingrese el país",
                    "Campo dinámico para la editorial", null, null, Dt("2026-03-12T01:55:31.7953332"), Dt("2026-03-20T08:36:56.2389161")),
                new(30, "Article", "GovernmentMatrixCode", "Código de matriz gubernamental", "string", "Dynamic",
                    null, null, null,
                    false, true, false, true, true,
                    true, true, 102, 100, "Ingrese el código",
                    "Campo dinámico requerido por matriz externa", null, null, Dt("2026-03-12T01:55:31.7953332"), null),
                new(31, "ArticleParticipant", "ScopusAuthorId", "ID de autor Scopus", "string", "Dynamic",
                    null, null, null,
                    false, true, false, true, true,
                    true, true, 100, 150, "Ingrese el id Scopus",
                    "Identificador externo del autor en Scopus", null, null, Dt("2026-03-12T01:56:15.3590713"), null),
                new(32, "ArticleParticipant", "CvLacId", "ID CvLAC", "string", "Dynamic",
                    null, null, null,
                    false, true, false, true, true,
                    true, true, 101, 150, "Ingrese el id CvLAC",
                    "Identificador académico del autor", null, null, Dt("2026-03-12T01:56:15.3590713"), null),
                new(34, "Article", "JournalName", "Nombre de revista", "string", "CompositeData",
                    "dbo.Venues", "Name", null,
                    true, false, true, true, true,
                    false, true, 160, 250, null,
                    "Nombre de la revista o venue.", null, null, Dt("2026-03-21T00:38:43.3452663"), null),
                new(35, "Article", "IssnCode", "ISSN", "string", "CompositeData",
                    "dbo.Venues", "IssnCode", null,
                    true, false, false, true, true,
                    false, true, 161, 50, null,
                    "ISSN o identificador editorial.", null, null, Dt("2026-03-21T00:38:43.4415045"), null),
                new(36, "Article", "IssueNumber", "Número", "string", "CompositeData",
                    "dbo.Venues", "IssueNumber", null,
                    true, false, false, true, true,
                    false, true, 162, 50, null,
                    "Número o issue de la revista.", null, null, Dt("2026-03-21T00:38:43.4445143"), null),
                new(37, "Article", "VolumeNumber", "Volumen", "string", "CompositeData",
                    "dbo.Venues", "VolumeNumber", null,
                    true, false, false, true, true,
                    false, true, 163, 50, null,
                    "Volumen de la revista.", null, null, Dt("2026-03-21T00:38:43.4447053"), null),
                new(38, "Article", "JournalUrl", "URL de revista", "string", "CompositeData",
                    "dbo.Venues", "JournalUrl", null,
                    true, false, false, true, true,
                    false, true, 164, 500, null,
                    "URL de la revista o del recurso editorial.", null, null, Dt("2026-03-21T00:38:43.4447808"), null),
                new(39, "Article", "Sjr", "SJR", "decimal", "CompositeData",
                    "dbo.VenueMetrics", "SJR", null,
                    true, false, false, true, true,
                    false, true, 165, null, null,
                    "Métrica SJR asociada al venue.", null, null, Dt("2026-03-21T00:38:43.4448429"), null),
                new(40, "Article", "Quartile", "Cuartil", "string", "CompositeData",
                    "dbo.VenueMetrics", "Quartile", null,
                    true, false, false, true, true,
                    false, true, 166, 20, null,
                    "Cuartil de la revista para el año del artículo.", null, null, Dt("2026-03-21T00:38:43.4448973"), null),
                new(1036, "Article", "FacultyId", "Facultad", "int", "Physical",
                    "Articles", "FacultyId", "Faculties",
                    true, false, false, true, true,
                    true, true, 180, null, "Seleccione la facultad institucional",
                    "Facultad responsable o asociada al registro del articulo.", null, null, Dt("2026-04-15T16:43:32.4179225"), null),
            ],
            [nameof(FieldCatalogRow.EntityName), nameof(FieldCatalogRow.FieldKey)]),
        new ArticlesCatalogSeedTable<FormDefinition, FormDefinitionRow>(
            "FormDefinitions", nameof(FormDefinitionRow.FormId),
            [
                new(1, "ArticleManualForm", "Registro manual de artículo", "Article", "Formulario principal para registro manual de artículos",
                    true, Dt("2026-03-12T01:37:40.8262658"), Dt("2026-06-01T04:48:42.3033175")),
                new(2, "ArticleParticipantForm", "Registro de autores del artículo", "ArticleParticipant", "Formulario para registrar autores y coautores",
                    true, Dt("2026-03-12T01:37:40.8262658"), Dt("2026-09-29T23:23:46.6892846")),
            ],
            [nameof(FormDefinitionRow.FormKey)]),
        new ArticlesCatalogSeedTable<FormFieldDefinition, FormFieldRow>(
            "FormFields", nameof(FormFieldRow.FormFieldId),
            [
                new(1, 1, 1, true, true, true,
                    1, "Identificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(4, 1, 4, true, true, true,
                    4, "Identificación", null, Dt("2026-03-12T01:38:26.8684282"), Dt("2026-03-27T07:25:26.8987050")),
                new(5, 1, 5, true, false, true,
                    5, "General", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(6, 1, 6, true, false, true,
                    6, "Publicación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(7, 1, 7, true, false, true,
                    7, "Publicación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(10, 1, 10, false, false, false,
                    10, "Publicación", null, Dt("2026-03-12T01:38:26.8684282"), Dt("2026-03-21T00:38:44.0174551")),
                new(11, 1, 11, true, false, true,
                    11, "Clasificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(12, 1, 12, true, false, true,
                    12, "Publicación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(13, 1, 13, true, false, true,
                    13, "Clasificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(14, 1, 14, true, false, true,
                    14, "Clasificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(15, 1, 15, true, false, true,
                    15, "Clasificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(16, 1, 16, true, false, true,
                    16, "Clasificación", null, Dt("2026-03-12T01:38:26.8684282"), null),
                new(17, 2, 17, true, true, true,
                    1, "Autoría", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(18, 2, 18, true, false, true,
                    2, "Identidad", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(19, 2, 19, true, true, true,
                    3, "Autoría", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(20, 2, 20, true, false, true,
                    4, "Autoría", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(21, 2, 21, true, false, true,
                    5, "Identidad", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(23, 2, 23, true, false, true,
                    7, "Autoría", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(26, 2, 26, true, false, true,
                    10, "Contacto e integración", null, Dt("2026-03-12T01:39:21.3294668"), null),
                new(38, 1, 38, true, false, true,
                    15, "Publicación", 2, Dt("2026-03-21T00:38:44.0337644"), null),
                new(39, 1, 39, true, false, true,
                    16, "Publicación", 1, Dt("2026-03-21T00:38:44.0338474"), null),
                new(1038, 1, 2, true, true, true,
                    100, null, null, Dt("2026-03-27T07:28:58.0072948"), Dt("2026-06-02T08:16:14.7691915")),
                new(2039, 1, 40, true, true, true,
                    100, null, null, Dt("2026-03-31T14:45:18.6548950"), Dt("2026-06-02T08:14:51.0530243")),
            ],
            [nameof(FormFieldRow.FormId), nameof(FormFieldRow.FieldId)]),
    ];

    private static DateTime Dt(string value)
        => DateTime.Parse(value, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
}

internal sealed record FieldCatalogRow(
    int FieldId, string EntityName, string FieldKey, string FieldLabel, string DataType, string SourceType,
    string? PhysicalTableName, string? PhysicalColumnName, string? ReferenceTableName,
    bool IsSystemField, bool IsDynamic, bool IsRequired, bool IsVisible, bool IsEditable,
    bool IsFilterable, bool IsActive, int DisplayOrder, int? MaxLength, string? Placeholder,
    string? HelpText, string? DefaultValue, string? ValidationRule, DateTime CreatedAt, DateTime? UpdatedAt);

internal sealed record FormDefinitionRow(
    int FormId, string FormKey, string FormName, string EntityName, string? Description,
    bool IsActive, DateTime CreatedAt, DateTime? UpdatedAt);

internal sealed record FormFieldRow(
    int FormFieldId, int FormId, int FieldId, bool IsVisible, bool IsRequired, bool IsEditable,
    int DisplayOrder, string? GroupName, int? ColumnSpan, DateTime CreatedAt, DateTime? UpdatedAt);
