// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tesisproject.backend.Data;

#nullable disable

namespace tesisproject.backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205081658_Fix_Product_Visit_Navigation")]
    partial class Fix_Product_Visit_Navigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AcademicPeriods");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Auth.AppUser", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("IdAsp")
                        .HasColumnType("int");

                    b.Property<int?>("IdLocal")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("IdAsp");

                    b.HasIndex("IdLocal");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("IsoAlpha3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.FundingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("FundingTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.GroupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GroupTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.IndexingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndexingSources");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique()
                        .HasFilter("[CountryId] IS NOT NULL");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.MemberRoleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Flag")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MemberRoleTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ObjectiveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ObjectiveTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProjectExtensionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBudgetExecutable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProjectExtensionTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProjectState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProjectStates");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchCategoryTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("ResearchCategoryTypeId");

                    b.ToTable("ResearchCategories");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategoryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ResearchCategoryGroups");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ResearchCategoryGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResearchCategoryGroupId");

                    b.ToTable("ResearchCategoryTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ScopeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ScopeTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.TransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.VisitState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("VisitStates");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("CertifiedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExecutedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FundingTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("BudgetId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("FundingTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.BudgetTransaction", b =>
                {
                    b.Property<int>("BudgetTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetTransactionId"));

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<string>("BudgetItem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CURNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificationDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("CertifiedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CertifiedAt")
                        .HasColumnType("date");

                    b.Property<int>("CertifiedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExecutedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("date");

                    b.Property<int?>("ExecutedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ExecutionDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("int");

                    b.HasKey("BudgetTransactionId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CertifiedByUserId");

                    b.HasIndex("ExecutedByUserId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("BudgetTransactions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Convocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Convocations");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ConvocationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvocationId")
                        .HasColumnType("int");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxDurationMonths")
                        .HasColumnType("int");

                    b.Property<int?>("MinDurationMonths")
                        .HasColumnType("int");

                    b.Property<int>("MinQuartile")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredInGroup")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConvocationId");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ConvocationId", "GroupCode");

                    b.HasIndex("ConvocationId", "ProductTypeId");

                    b.HasIndex("MinDurationMonths", "MaxDurationMonths");

                    b.ToTable("ConvocationRules");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ConvocationRuleIndexing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvocationRuleId")
                        .HasColumnType("int");

                    b.Property<int>("IndexingSourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndexingSourceId");

                    b.HasIndex("ConvocationRuleId", "IndexingSourceId")
                        .IsUnique();

                    b.ToTable("ConvocationRuleIndexing");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ResolutionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RelatedDocumentId")
                        .IsUnique()
                        .HasFilter("[RelatedDocumentId] IS NOT NULL");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ExternalResearcher", b =>
                {
                    b.Property<int>("ExternalResearcherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalResearcherId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ExternalResearcherId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("ExternalResearchers");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ExternalResearcherProject", b =>
                {
                    b.Property<int>("ExternalResearcherProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExternalResearcherProjectId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExternalResearcherId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExternalResearcherProjectId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExternalResearcherId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ExternalResearcherProjects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("GroupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupTypeId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("GroupId");

                    b.HasIndex("MemberRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ObjectiveActivity", b =>
                {
                    b.Property<int>("ObjectiveActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjectiveActivityId"));

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ActivityResult")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasMaxLength(1000)
                        .HasColumnType("bit");

                    b.Property<int>("ObjectiveId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ObjectiveActivityId");

                    b.HasIndex("ObjectiveId");

                    b.ToTable("ObjectiveActivities");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ObjectiveActivityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObjectiveActivityId")
                        .HasColumnType("int");

                    b.Property<string>("ReportNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<double?>("WeeklyHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveActivityId");

                    b.HasIndex("VisitId");

                    b.ToTable("ObjectiveActivityUsers");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VisitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductAttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int>("ProductAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductAttributeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductAttributeDefinitions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProductId", "UserId")
                        .IsUnique();

                    b.ToTable("ProductAuthors");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("ProductAttributeId");

                    b.HasIndex("ProductId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("ProductValues");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<int>("ConvocationId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("int");

                    b.Property<decimal?>("ExecutionPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int?>("InitialDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProjectGroupId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectStateId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RealEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TentativeEndDate")
                        .HasColumnType("date");

                    b.HasKey("ProjectId");

                    b.HasIndex("ConvocationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("InitialDocumentId");

                    b.HasIndex("ProjectGroupId");

                    b.HasIndex("ProjectStateId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectExtension", b =>
                {
                    b.Property<int>("ProjectExtensionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectExtensionId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectExtensionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectExtensionId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ProjectExtensionTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectExtensions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ObjectiveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Objetive")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("WeightedPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ObjectiveTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectObjectives");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectResearchCategory", b =>
                {
                    b.Property<int>("ProjectResearchCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectResearchCategoryId"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ResearchCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProjectResearchCategoryId");

                    b.HasIndex("ResearchCategoryId");

                    b.HasIndex("ProjectId", "ResearchCategoryId")
                        .IsUnique();

                    b.ToTable("ProjectResearchCategories");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectScope", b =>
                {
                    b.Property<int>("ProjectScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectScopeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProjectScopeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScopeTypeId");

                    b.ToTable("ProjectScopes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.UserFacultyScope", b =>
                {
                    b.Property<int>("UserFacultyScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFacultyScopeId"));

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdentityUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserFacultyScopeId");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserFacultyScopes");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int>("AcademicPeriodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("FundingDocumentId")
                        .HasColumnType("int");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PerformedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProgressDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitStateId")
                        .HasColumnType("int");

                    b.HasKey("VisitId");

                    b.HasIndex("AcademicPeriodId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FundingDocumentId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("ProgressDocumentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VisitStateId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.VisitIssue", b =>
                {
                    b.Property<int>("VisitIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitIssueId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitIssueId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitIssues");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Auth.AppUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("IdLocal")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.Institution", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.Country", "Country")
                        .WithMany("Institutions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategory", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.ResearchCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ResearchCategoryType", "ResearchCategoryType")
                        .WithMany("ResearchCategories")
                        .HasForeignKey("ResearchCategoryTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentCategory");

                    b.Navigation("ResearchCategoryType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategoryType", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.ResearchCategoryGroup", "ResearchCategoryGroup")
                        .WithMany("Types")
                        .HasForeignKey("ResearchCategoryGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ResearchCategoryGroup");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Budget", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.FundingType", "FundingType")
                        .WithMany()
                        .HasForeignKey("FundingTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("Budgets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FundingType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.BudgetTransaction", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Budget", "Budget")
                        .WithMany("Transactions")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CertifiedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ExecutedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Catalogs.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ConvocationRule", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Convocation", "Convocation")
                        .WithMany("Rules")
                        .HasForeignKey("ConvocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProductType", null)
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Convocation");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ConvocationRuleIndexing", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.ConvocationRule", "ConvocationRule")
                        .WithMany("AllowedIndexings")
                        .HasForeignKey("ConvocationRuleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.IndexingSource", "IndexingSource")
                        .WithMany()
                        .HasForeignKey("IndexingSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConvocationRule");

                    b.Navigation("IndexingSource");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Document", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Document", "RelatedDocument")
                        .WithOne("ReverseRelation")
                        .HasForeignKey("tesisproject.shared.Entities.Core.Document", "RelatedDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DocumentType");

                    b.Navigation("RelatedDocument");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ExternalResearcher", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ExternalResearcherProject", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.ExternalResearcher", "ExternalResearcher")
                        .WithMany("ExternalResearcherProjects")
                        .HasForeignKey("ExternalResearcherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("ExternalResearcherProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExternalResearcher");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Group", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.GroupType", "GroupType")
                        .WithMany()
                        .HasForeignKey("GroupTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.GroupMember", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.MemberRoleType", "MemberRole")
                        .WithMany()
                        .HasForeignKey("MemberRoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MemberRole");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ObjectiveActivity", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.ProjectObjective", "Objective")
                        .WithMany("Activities")
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ObjectiveActivityUser", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.ObjectiveActivity", "ObjectiveActivity")
                        .WithMany("ResponsibleUsers")
                        .HasForeignKey("ObjectiveActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Visit", "Visit")
                        .WithMany()
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectiveActivity");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.Product", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("Products")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Visit", "Visit")
                        .WithMany("Products")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ProductType");

                    b.Navigation("Project");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductAttributeDefinition", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProductAttribute", "ProductAttribute")
                        .WithMany("TypeDefinitions")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductAttribute");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductAuthor", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Products.Product", "Product")
                        .WithMany("Authors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductValue", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Products.ProductAttributeDefinition", "AttributeDefinition")
                        .WithMany("ProductValues")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProductAttribute", null)
                        .WithMany("Values")
                        .HasForeignKey("ProductAttributeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Core.Products.Product", "Product")
                        .WithMany("Values")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Project", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Convocation", "Convocation")
                        .WithMany("Projects")
                        .HasForeignKey("ConvocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Document", "InitialDocument")
                        .WithMany()
                        .HasForeignKey("InitialDocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Core.Group", "ProjectGroup")
                        .WithMany()
                        .HasForeignKey("ProjectGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProjectState", "ProjectState")
                        .WithMany()
                        .HasForeignKey("ProjectStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Convocation");

                    b.Navigation("InitialDocument");

                    b.Navigation("ProjectGroup");

                    b.Navigation("ProjectState");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectExtension", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ProjectExtensionType", "ProjectExtensionType")
                        .WithMany()
                        .HasForeignKey("ProjectExtensionTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Project");

                    b.Navigation("ProjectExtensionType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectObjective", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Catalogs.ObjectiveType", "ObjectiveType")
                        .WithMany()
                        .HasForeignKey("ObjectiveTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("ProjectObjectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ObjectiveType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectResearchCategory", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("ProjectResearchCategories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ResearchCategory", "ResearchCategory")
                        .WithMany("ProjectResearchCategories")
                        .HasForeignKey("ResearchCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ResearchCategory");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectScope", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.ScopeType", "ScopeType")
                        .WithMany()
                        .HasForeignKey("ScopeTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ScopeType");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.UserFacultyScope", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Visit", b =>
                {
                    b.HasOne("AcademicPeriod", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Core.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Visits_Documents_DocumentId");

                    b.HasOne("tesisproject.shared.Entities.Core.Document", "FundingDocument")
                        .WithMany()
                        .HasForeignKey("FundingDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Visits_Documents_FundingDocumentId");

                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Core.Document", "ProgressDocument")
                        .WithMany()
                        .HasForeignKey("ProgressDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Visits_Documents_ProgressDocumentId");

                    b.HasOne("tesisproject.shared.Entities.Core.Project", "Project")
                        .WithMany("Visits")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("tesisproject.shared.Entities.Catalogs.VisitState", "VisitState")
                        .WithMany()
                        .HasForeignKey("VisitStateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Document");

                    b.Navigation("FundingDocument");

                    b.Navigation("ProgressDocument");

                    b.Navigation("Project");

                    b.Navigation("VisitState");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.VisitIssue", b =>
                {
                    b.HasOne("tesisproject.shared.Entities.Auth.AppUser", null)
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.shared.Entities.Core.Visit", "Visit")
                        .WithMany("Issues")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.Country", b =>
                {
                    b.Navigation("Institutions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ProductAttribute", b =>
                {
                    b.Navigation("TypeDefinitions");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategory", b =>
                {
                    b.Navigation("ProjectResearchCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategoryGroup", b =>
                {
                    b.Navigation("Types");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Catalogs.ResearchCategoryType", b =>
                {
                    b.Navigation("ResearchCategories");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Budget", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Convocation", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ConvocationRule", b =>
                {
                    b.Navigation("AllowedIndexings");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Document", b =>
                {
                    b.Navigation("ReverseRelation");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ExternalResearcher", b =>
                {
                    b.Navigation("ExternalResearcherProjects");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ObjectiveActivity", b =>
                {
                    b.Navigation("ResponsibleUsers");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.Product", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Products.ProductAttributeDefinition", b =>
                {
                    b.Navigation("ProductValues");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Project", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("ExternalResearcherProjects");

                    b.Navigation("Products");

                    b.Navigation("ProjectObjectives");

                    b.Navigation("ProjectResearchCategories");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.ProjectObjective", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("tesisproject.shared.Entities.Core.Visit", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
