// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tesisproject.backend.Data;

#nullable disable

namespace tesisproject.backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicTermId")
                        .HasColumnType("int");

                    b.Property<int?>("BroadFieldId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DetailedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Doi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Filiacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("HasInterculturalComponent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpenAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsProjectResult")
                        .HasColumnType("bit");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Proceedings")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ProceedingsName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte?>("PublicationStatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("PublicationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResearchLineId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecificFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("AcademicTermId");

                    b.HasIndex("BroadFieldId");

                    b.HasIndex("DetailedFieldId");

                    b.HasIndex("Doi")
                        .IsUnique()
                        .HasDatabaseName("UX_Articles_Doi_NotBlank")
                        .HasFilter("[Doi] IS NOT NULL AND [Doi] <> N''");

                    b.HasIndex("PublicationStatusId");

                    b.HasIndex("ResearchLineId");

                    b.HasIndex("SpecificFieldId");

                    b.HasIndex("VenueId");

                    b.HasIndex("Title", "Year", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("UX_Articles_TitleYearVenue_NoDoi")
                        .HasFilter("[Doi] IS NULL");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.AcademicTerm", b =>
                {
                    b.Property<int>("AcademicTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcademicTermId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AcademicTermId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AcademicTerms");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleFile", b =>
                {
                    b.Property<int>("ArticleFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleFileId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ArticleFileId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleFiles");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleIndexing", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("IndexingSourceId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "IndexingSourceId");

                    b.HasIndex("IndexingSourceId");

                    b.ToTable("ArticleIndexings");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalAuthorId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Identificacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int?>("InstitutionalPersonId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimaryAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Orcid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Participacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ParticipantType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Index")
                        .IsUnique();

                    b.ToTable("ArticleParticipants");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleParticipantDynamicFieldValue", b =>
                {
                    b.Property<int>("ArticleParticipantDynamicFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleParticipantDynamicFieldValueId"));

                    b.Property<int>("ArticleParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValueBit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleParticipantDynamicFieldValueId");

                    b.HasIndex("ArticleParticipantId");

                    b.HasIndex("FieldId");

                    b.ToTable("ArticleParticipantDynamicFieldValues", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("EntityName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.BroadField", b =>
                {
                    b.Property<int>("BroadFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BroadFieldId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BroadFieldId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BroadFields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DetailedField", b =>
                {
                    b.Property<int>("DetailedFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailedFieldId"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SpecificFieldId")
                        .HasColumnType("int");

                    b.HasKey("DetailedFieldId");

                    b.HasIndex("SpecificFieldId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DetailedField_Specific_Code")
                        .HasFilter("[Code] IS NOT NULL AND [Code] <> N''");

                    b.HasIndex("SpecificFieldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_DetailedField_Specific_Name");

                    b.ToTable("DetailedFields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DynamicFieldOption", b =>
                {
                    b.Property<int>("DynamicFieldOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DynamicFieldOptionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DynamicFieldOptionId");

                    b.HasIndex("FieldId");

                    b.ToTable("DynamicFieldOptions", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DynamicFieldValue", b =>
                {
                    b.Property<int>("DynamicFieldValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DynamicFieldValueId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ValueBit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ValueInt")
                        .HasColumnType("int");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DynamicFieldValueId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("FieldId");

                    b.ToTable("DynamicFieldValues", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FieldCatalogEntry", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemField")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalColumnName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhysicalTableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReferenceTableName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationRule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FieldId");

                    b.ToTable("FieldCatalog", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FormDefinition", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FormId");

                    b.ToTable("FormDefinitions", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FormFieldDefinition", b =>
                {
                    b.Property<int>("FormFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormFieldId"));

                    b.Property<int?>("ColumnSpan")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FormFieldId");

                    b.HasIndex("FieldId");

                    b.HasIndex("FormId");

                    b.ToTable("FormFields", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatch", b =>
                {
                    b.Property<int>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBatchId"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ErrorRows")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SuccessfulRows")
                        .HasColumnType("int");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int");

                    b.HasKey("ImportBatchId");

                    b.ToTable("ImportBatch", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchError", b =>
                {
                    b.Property<int>("ImportBatchErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBatchErrorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<int?>("ImportBatchRowId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ImportBatchErrorId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ImportBatchRowId");

                    b.ToTable("ImportBatchError", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchRow", b =>
                {
                    b.Property<int>("ImportBatchRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBatchRowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("RawJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("RowStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TargetArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ImportBatchRowId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportBatchRow", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchRowValue", b =>
                {
                    b.Property<int>("ImportBatchRowValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportBatchRowValueId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("ImportBatchRowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValueType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ImportBatchRowValueId");

                    b.HasIndex("FieldId");

                    b.HasIndex("ImportBatchRowId");

                    b.ToTable("ImportBatchRowValue", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.IndexingSource", b =>
                {
                    b.Property<int>("IndexingSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndexingSourceId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IndexingSourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("IndexingSources");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.PublicationStatus", b =>
                {
                    b.Property<byte>("PublicationStatusId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PublicationStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PublicationStatuses");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrix", b =>
                {
                    b.Property<int>("RegistrationMatrixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationMatrixId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LastImportBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrationMatrixId");

                    b.HasIndex("LastImportBatchId");

                    b.ToTable("RegistrationMatrix", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixCell", b =>
                {
                    b.Property<int>("RegistrationMatrixCellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationMatrixCellId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("RawValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("RegistrationMatrixRowId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrationMatrixCellId");

                    b.HasIndex("FieldId");

                    b.HasIndex("RegistrationMatrixRowId", "FieldId")
                        .IsUnique();

                    b.ToTable("RegistrationMatrixCell", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixColumn", b =>
                {
                    b.Property<int>("RegistrationMatrixColumnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationMatrixColumnId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationMatrixId")
                        .HasColumnType("int");

                    b.Property<int>("WidthUnits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("RegistrationMatrixColumnId");

                    b.HasIndex("FieldId");

                    b.HasIndex("RegistrationMatrixId", "FieldId")
                        .IsUnique();

                    b.ToTable("RegistrationMatrixColumn", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixRow", b =>
                {
                    b.Property<int>("RegistrationMatrixRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationMatrixRowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistrationMatrixId")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RegistrationMatrixRowId");

                    b.HasIndex("RegistrationMatrixId", "RowNumber")
                        .IsUnique();

                    b.ToTable("RegistrationMatrixRow", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ResearchLine", b =>
                {
                    b.Property<int>("ResearchLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchLineId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ResearchLineId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResearchLines");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.SpecificField", b =>
                {
                    b.Property<int>("SpecificFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecificFieldId"));

                    b.Property<int>("BroadFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SpecificFieldId");

                    b.HasIndex("BroadFieldId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SpecificField_Broad_Code")
                        .HasFilter("[Code] IS NOT NULL AND [Code] <> N''");

                    b.HasIndex("BroadFieldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_SpecificField_Broad_Name");

                    b.ToTable("SpecificFields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("IssnCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IssueNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JournalUrl")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Journal");

                    b.Property<string>("VolumeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VenueId");

                    b.HasIndex("Name", "IssnCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Venue_Name_Issn")
                        .HasFilter("[IssnCode] IS NOT NULL");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.VenueMetric", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.Property<string>("Quartile")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("SJR")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("VenueId", "Year");

                    b.ToTable("VenueMetrics");
                });

            modelBuilder.Entity("tesisproject.backend.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("tesisproject.backend.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Article", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.AcademicTerm", "AcademicTerm")
                        .WithMany("Articles")
                        .HasForeignKey("AcademicTermId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tesisproject.backend.Data.Entities.BroadField", "BroadField")
                        .WithMany()
                        .HasForeignKey("BroadFieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.backend.Data.Entities.DetailedField", "DetailedField")
                        .WithMany()
                        .HasForeignKey("DetailedFieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.backend.Data.Entities.PublicationStatus", "PublicationStatus")
                        .WithMany("Articles")
                        .HasForeignKey("PublicationStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tesisproject.backend.Data.Entities.ResearchLine", "ResearchLine")
                        .WithMany("Articles")
                        .HasForeignKey("ResearchLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("tesisproject.backend.Data.Entities.SpecificField", "SpecificField")
                        .WithMany()
                        .HasForeignKey("SpecificFieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.backend.Data.Entities.Venue", "Venue")
                        .WithMany("Articles")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcademicTerm");

                    b.Navigation("BroadField");

                    b.Navigation("DetailedField");

                    b.Navigation("PublicationStatus");

                    b.Navigation("ResearchLine");

                    b.Navigation("SpecificField");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("tesisproject.backend.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("tesisproject.backend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("tesisproject.backend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("tesisproject.backend.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("tesisproject.backend.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleFile", b =>
                {
                    b.HasOne("Article", "Article")
                        .WithMany("Files")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleIndexing", b =>
                {
                    b.HasOne("Article", "Article")
                        .WithMany("Indexings")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.IndexingSource", "IndexingSource")
                        .WithMany("ArticleIndexings")
                        .HasForeignKey("IndexingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("IndexingSource");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleParticipant", b =>
                {
                    b.HasOne("Article", "Article")
                        .WithMany("Participants")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleParticipantDynamicFieldValue", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.ArticleParticipant", "ArticleParticipant")
                        .WithMany("DynamicFieldValues")
                        .HasForeignKey("ArticleParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleParticipant");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DetailedField", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.SpecificField", "SpecificField")
                        .WithMany("DetailedFields")
                        .HasForeignKey("SpecificFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificField");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DynamicFieldOption", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany("Options")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.DynamicFieldValue", b =>
                {
                    b.HasOne("Article", "Article")
                        .WithMany("DynamicFieldValues")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FormFieldDefinition", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany("FormFields")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.FormDefinition", "Form")
                        .WithMany("Fields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchError", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("tesisproject.backend.Data.Entities.ImportBatch", "Batch")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.ImportBatchRow", "Row")
                        .WithMany("Errors")
                        .HasForeignKey("ImportBatchRowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Batch");

                    b.Navigation("Field");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchRow", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.ImportBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchRowValue", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.ImportBatchRow", "Row")
                        .WithMany("Values")
                        .HasForeignKey("ImportBatchRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrix", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.ImportBatch", "LastImportBatch")
                        .WithMany()
                        .HasForeignKey("LastImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastImportBatch");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixCell", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.RegistrationMatrixRow", "Row")
                        .WithMany("Cells")
                        .HasForeignKey("RegistrationMatrixRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixColumn", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.FieldCatalogEntry", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("tesisproject.backend.Data.Entities.RegistrationMatrix", "Matrix")
                        .WithMany("Columns")
                        .HasForeignKey("RegistrationMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixRow", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.RegistrationMatrix", "Matrix")
                        .WithMany("Rows")
                        .HasForeignKey("RegistrationMatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.SpecificField", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.BroadField", "BroadField")
                        .WithMany("SpecificFields")
                        .HasForeignKey("BroadFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BroadField");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.VenueMetric", b =>
                {
                    b.HasOne("tesisproject.backend.Data.Entities.Venue", "Venue")
                        .WithMany("VenueMetrics")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Article", b =>
                {
                    b.Navigation("DynamicFieldValues");

                    b.Navigation("Files");

                    b.Navigation("Indexings");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.AcademicTerm", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ArticleParticipant", b =>
                {
                    b.Navigation("DynamicFieldValues");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.BroadField", b =>
                {
                    b.Navigation("SpecificFields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FieldCatalogEntry", b =>
                {
                    b.Navigation("FormFields");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.FormDefinition", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatch", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ImportBatchRow", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.IndexingSource", b =>
                {
                    b.Navigation("ArticleIndexings");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.PublicationStatus", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrix", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.RegistrationMatrixRow", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.ResearchLine", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.SpecificField", b =>
                {
                    b.Navigation("DetailedFields");
                });

            modelBuilder.Entity("tesisproject.backend.Data.Entities.Venue", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("VenueMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
